<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#library" data-toc-modified-id="library-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>library</a></span></li><li><span><a href="#data-('조건df.csv')" data-toc-modified-id="data-('조건df.csv')-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>data ('조건df.csv')</a></span></li><li><span><a href="#mk_cd-함수" data-toc-modified-id="mk_cd-함수-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>mk_cd 함수</a></span></li><li><span><a href="#data-('보조지표추가_cd_nuniq=2348.ftr')" data-toc-modified-id="data-('보조지표추가_cd_nuniq=2348.ftr')-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>data ('보조지표추가_cd_nuniq=2348.ftr')</a></span></li><li><span><a href="#data-('조건만족cd_dt-(by-ffin).txt')" data-toc-modified-id="data-('조건만족cd_dt-(by-ffin).txt')-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>data ('조건만족cd_dt (by ffin).txt')</a></span></li></ul></div>

# library

In [17]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# data ('조건df.csv')

In [6]:
조건df = pd.read_csv('조건df.csv')
조건df['code'].nunique()

2377

# mk_cd 함수

In [3]:
def mk_cd(x):
    if type(x) == str:
        if x.isalpha():
            return x
        else:
            if len(x) == 6:
                return x
            else:
                return "0"*(6-len(x))+x
    elif type(x) == int:
        x = str(x)
        return "0"*(6-len(x))+x

In [4]:
조건df['code'] = list(map(mk_cd, 조건df['code']))

In [5]:
조건df['code'].nunique()

2371

# data ('보조지표추가_cd_nuniq=2348.ftr')

In [42]:
보조지표df = pd.read_feather('보조지표추가_cd_nuniq=2348.ftr', columns = None, use_threads = True)

In [43]:
보조지표df

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
0,19960701,000010,36496,37676,36496,37588,14499,542221500,1.18,NaN,...,0.000000,0.000000,0.000000,92.542373,-7.457627,0.000000,37588.000000,0.000000,0.000000,0.000000
1,19960702,000010,37588,38462,37151,37938,30476,1153293600,0.93,NaN,...,0.000000,100.000000,31.593737,73.346897,-26.653103,0.000000,37743.555556,0.000000,0.074228,8.127021
2,19960703,000010,38025,38025,37151,37719,18375,694638000,-0.58,NaN,...,0.000000,98.619124,40.267459,62.207528,-37.792472,0.000000,37732.880541,0.000000,0.085075,8.142756
3,19960704,000010,37719,37938,37151,37370,22539,849041000,-0.93,NaN,...,0.000000,95.325955,37.909441,44.455748,-55.544252,0.000000,37580.577800,0.000000,0.018624,9.925574
4,19960705,000010,37151,38025,37151,38025,15830,595899300,1.75,37728.0,...,0.000000,92.826559,48.706725,77.772126,-22.227874,0.000000,37767.295870,0.000000,0.105182,8.153143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6854873,20220325,950210,19400,21050,17250,17750,2884592,55832885600,-3.01,15730.0,...,0.886111,2.571420,54.711042,59.756098,-40.243902,659.264706,15704.276412,31.481481,0.730444,66.393691
6854874,20220328,950210,17650,18150,17450,18050,432272,7718272800,1.69,16510.0,...,0.918642,8.403671,55.985908,63.414634,-36.585366,1297.205882,16198.537285,33.210332,2.130543,56.425429
6854875,20220329,950210,17900,21400,17500,19800,5156123,103299163150,9.70,17600.0,...,1.000000,15.800461,55.988631,81.286550,-18.713450,2238.676471,17076.125215,40.425532,4.034409,75.501358
6854876,20220330,950210,20250,22500,19450,19800,2072532,43571439650,0.00,18740.0,...,1.000000,21.143478,50.227010,72.020725,-27.979275,3473.676471,17737.179572,48.872180,5.409680,68.857624
6854877,20220331,950210,19500,20500,19150,20300,511003,10140785700,2.53,19140.0,...,1.000000,25.885194,52.108588,77.202073,-22.797927,4133.382353,18361.675910,49.264706,6.603329,56.740704

In [9]:
보조지표df['code'].nunique()

2348

In [15]:
보조지표df['code'] = pd.DataFrame(map(mk_cd,보조지표df['code']))

In [16]:
보조지표df['code'].nunique()

2348

In [29]:
보조지표df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6854878 entries, 0 to 6854877
Data columns (total 58 columns):
 #   Column         Dtype
---  ------         -----
 0   date           int64
 1   code           object
 2   open           int64
 3   high           int64
 4   low            int64
 5   close          int64
 6   volume         int64
 7   tradingvalue   int64
 8   change         float64
 9   ma_5           float64
 10  ma_20          float64
 11  ma_60          float64
 12  ma_120         float64
 13  MFI            float64
 14  ADI            float64
 15  OBV            int64
 16  CMF            float64
 17  FI             float64
 18  EOM, EMV       float64
 19  VPT            float64
 20  NVI            float64
 21  VMAP           float64
 22  ATR            float64
 23  BHB            float64
 24  BLB            float64
 25  KCH            float64
 26  KCL            float64
 27  KCM            float64
 28  DCH            float64
 29  DCL            float64
 30  DCM            float64
 31  UI             float64
 32  SMA            float64
 33  EMA            float64
 34  WMA            float64
 35  MACD           float64
 36  ADX            float64
 37  -VI            float64
 38  +VI            float64
 39  TRIX           float64
 40  MI             float64
 41  CCI            float64
 42  DPO            float64
 43  KST            float64
 44  Ichimoku       float64
 45  Parabolic SAR  float64
 46  STC            float64
 47  RSI            float64
 48  SRSI           float64
 49  TSI            float64
 50  UO             float64
 51  SR             float64
 52  WR             float64
 53  AO             float64
 54  KAMA           float64
 55  ROC            float64
 56  PPO            float64
 57  PVO            float64
dtypes: float64(49), int64(8), object(1)
memory usage: 3.0+ GB

# data ('조건만족cd_dt (by ffin).txt')

In [19]:
f = open('조건만족cd_dt (by ffin).txt', 'r', encoding = 'utf-8')
l = f.readlines()

In [41]:
for iter, i in tqdm(enumerate(l)):
    i = i.strip()
    i = i.split('\t') # 문자열로 나옴
    cd = i[0]
    dt = i[1]
    if iter == 0:
        pass
    else:
        dt = int(dt)
#         보조지표df.iloc[np.where((보조지표df['code'] == cd) & (보조지표df['date'] == dt))] # 각 조건 괄호로 묶어줘야 결과 출력됨.
        조건idx = 보조지표df.iloc[np.where((보조지표df['code'] == cd) & (보조지표df['date'] == dt))].index.values[0]
        보조지표df.iloc[조건idx-9:조건idx+1]
f.close()

0it [00:00, ?it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
59,19960910,000010,37807,38113,37676,37850,17585,666446300,0.46,37623.0,...,1.000000,11.301074,58.207669,90.906389,-9.093611,973.867647,36610.826858,8.248012,0.825861,17.541632
60,19960911,000010,37850,38025,37457,37850,19569,738559900,0.00,37736.6,...,1.000000,13.150384,61.194620,90.906389,-9.093611,1016.435294,36703.617782,7.979346,0.962022,12.667179
61,19960912,000010,37588,37850,37239,37807,18725,704567800,-0.12,37754.2,...,0.978614,14.540704,57.077550,89.059561,-10.940439,1048.376471,36797.189212,5.617946,1.047693,8.338236
62,19960913,000010,37763,37763,37195,37282,23287,870083500,-1.39,37693.0,...,0.667843,14.031414,56.837611,71.833709,-28.166291,962.402941,36875.621471,2.400571,0.989763,6.016700
63,19960914,000010,37151,37239,36801,37151,16167,599686900,-0.35,37588.0,...,0.596138,13.195258,51.944891,66.184388,-33.815612,814.035294,36917.737833,2.409240,0.904950,1.995936
64,19960916,000010,37064,37719,37064,37326,22166,830147600,0.47,37483.2,...,0.680551,12.940648,53.541998,72.072678,-27.927322,701.861765,36920.354933,5.823316,0.865741,0.530428
65,19960917,000010,37195,37719,37195,37719,16636,622768400,1.05,37457.0,...,0.860703,13.729078,58.179802,85.296097,-14.703903,639.914706,36949.186036,7.204980,0.909286,-2.422356
66,19960918,000010,37588,37807,37588,37719,22616,853064600,0.00,37439.4,...,0.860703,14.380319,61.261600,85.296097,-14.703903,670.514706,36952.390256,1.172147,0.932735,-2.831470
67,19960919,000010,37807,37807,37151,37282,27309,1020187000,-1.16,37439.4,...,0.000000,13.395265,56.271576,39.389736,-60.610264,672.441176,36960.643488,0.000000,0.846921,-1.586533
68,19960920,000010,37151,37370,35403,36277,42732,1548596200,-2.70,37264.6,...,0.000000,9.148998,48.350147,31.747185,-68.252815,570.800000,36873.652994,-3.823007,0.554780,4.094900

2it [00:00,  7.11it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
65,19960917,000010,37195,37719,37195,37719,16636,622768400,1.05,37457.0,...,0.860703,13.729078,58.179802,85.296097,-14.703903,639.914706,36949.186036,7.204980,0.909286,-2.422356
66,19960918,000010,37588,37807,37588,37719,22616,853064600,0.00,37439.4,...,0.860703,14.380319,61.261600,85.296097,-14.703903,670.514706,36952.390256,1.172147,0.932735,-2.831470
67,19960919,000010,37807,37807,37151,37282,27309,1020187000,-1.16,37439.4,...,0.000000,13.395265,56.271576,39.389736,-60.610264,672.441176,36960.643488,0.000000,0.846921,-1.586533
68,19960920,000010,37151,37370,35403,36277,42732,1548596200,-2.70,37264.6,...,0.000000,9.148998,48.350147,31.747185,-68.252815,570.800000,36873.652994,-3.823007,0.554780,4.094900
69,19960921,000010,36146,37588,35621,37413,24493,889436100,3.13,37282.0,...,0.577202,8.941536,60.968544,73.011260,-26.988740,426.914706,36883.186762,-0.465574,0.563154,2.925305
70,19960923,000010,37588,38244,36889,38025,68792,2588880000,1.64,37343.2,...,0.821257,10.386259,63.134661,92.291447,-7.708553,429.535294,36892.060948,0.926319,0.694182,13.791220
71,19960924,000010,37632,38681,37632,38681,40918,1565992200,1.72,37535.6,...,1.000000,13.105788,69.232814,100.000000,-0.000000,488.555882,36942.743774,2.195509,0.927977,14.395439
72,19960925,000010,38681,40211,38681,39817,47592,1879652900,2.94,38042.6,...,1.000000,17.747679,69.199878,91.805324,-8.194676,824.102941,37261.869877,5.196830,1.338924,16.088133
73,19960930,000010,40211,40298,38899,39336,40746,1606384300,-1.21,38654.4,...,0.817747,19.686386,64.941677,80.347293,-19.652707,1394.532353,37427.600218,4.044225,1.540871,15.617985
74,19961001,000010,40211,40211,37195,37501,835032,33396100000,-4.67,38672.0,...,0.273435,15.743477,54.854891,42.860061,-57.139939,1756.379412,37428.049275,0.587415,1.295706,74.523403

3it [00:00,  4.75it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
69,19960921,000010,36146,37588,35621,37413,24493,889436100,3.13,37282.0,...,0.577202,8.941536,60.968544,73.011260,-26.988740,426.914706,36883.186762,-0.465574,0.563154,2.925305
70,19960923,000010,37588,38244,36889,38025,68792,2588880000,1.64,37343.2,...,0.821257,10.386259,63.134661,92.291447,-7.708553,429.535294,36892.060948,0.926319,0.694182,13.791220
71,19960924,000010,37632,38681,37632,38681,40918,1565992200,1.72,37535.6,...,1.000000,13.105788,69.232814,100.000000,-0.000000,488.555882,36942.743774,2.195509,0.927977,14.395439
72,19960925,000010,38681,40211,38681,39817,47592,1879652900,2.94,38042.6,...,1.000000,17.747679,69.199878,91.805324,-8.194676,824.102941,37261.869877,5.196830,1.338924,16.088133
73,19960930,000010,40211,40298,38899,39336,40746,1606384300,-1.21,38654.4,...,0.817747,19.686386,64.941677,80.347293,-19.652707,1394.532353,37427.600218,4.044225,1.540871,15.617985
74,19961001,000010,40211,40211,37195,37501,835032,33396100000,-4.67,38672.0,...,0.273435,15.743477,54.854891,42.860061,-57.139939,1756.379412,37428.049275,0.587415,1.295706,74.523403
75,19961002,000010,37544,38156,36933,37588,38760,1454308800,0.23,38584.6,...,0.294948,13.087764,55.548750,44.637385,-55.362615,1717.905882,37428.953742,1.176281,1.107145,61.065152
76,19961004,000010,37151,37544,36277,36277,26433,971372600,-3.49,38103.8,...,0.000000,7.847437,47.095991,17.854954,-82.145046,1446.205882,37397.832063,-2.810373,0.669986,48.612846
77,19961005,000010,35840,36277,35840,36277,12186,439212800,0.00,37395.8,...,0.000000,3.992908,45.480535,17.854954,-82.145046,763.558824,37376.552135,-3.823007,0.318417,36.641917
78,19961007,000010,36496,38375,36496,37588,31889,1187210600,3.61,37046.2,...,0.332074,3.767677,45.085356,44.637385,-55.362615,273.105882,37381.743166,-0.347305,0.317907,27.495080

4it [00:00,  4.05it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
114,19961118,000010,31513,32999,31513,32125,10401,338695300,-3.42,31993.4,...,0.684484,-32.649264,40.405083,21.505906,-78.494094,-2994.302941,32483.129997,-4.546130,-3.318101,-32.379078
115,19961119,000010,32125,32518,31513,31906,12202,390575800,-0.68,32028.4,...,0.629689,-31.347183,42.675353,19.981696,-80.018304,-2891.258824,32467.995440,-3.566463,-3.259838,-30.898716
116,19961120,000010,31950,31950,31469,31469,5077,160634200,-1.37,32037.2,...,0.521765,-30.997163,39.732711,9.068220,-90.931780,-2723.061765,32429.424712,-5.637350,-3.285685,-33.670946
117,19961121,000010,31076,31688,30639,30814,15542,484923300,-2.08,31915.0,...,0.371316,-31.687793,40.481815,5.802387,-94.197613,-2624.911765,32381.223704,-6.249239,-3.432579,-29.409709
118,19961122,000010,30814,30814,29939,30027,14977,455705000,-2.55,31268.2,...,0.210548,-33.340976,38.547094,2.368138,-97.631862,-2773.829412,32246.365480,-8.643666,-3.708826,-26.050503
119,19961125,000010,30158,30158,29065,29065,18338,540928700,-3.20,30656.2,...,0.041562,-35.910457,35.772438,0.000000,-100.000000,-3077.126471,31838.077635,-8.904281,-4.132517,-21.184721
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891

5it [00:01,  3.72it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
117,19961121,000010,31076,31688,30639,30814,15542,484923300,-2.08,31915.0,...,0.371316,-31.687793,40.481815,5.802387,-94.197613,-2624.911765,32381.223704,-6.249239,-3.432579,-29.409709
118,19961122,000010,30814,30814,29939,30027,14977,455705000,-2.55,31268.2,...,0.210548,-33.340976,38.547094,2.368138,-97.631862,-2773.829412,32246.365480,-8.643666,-3.708826,-26.050503
119,19961125,000010,30158,30158,29065,29065,18338,540928700,-3.20,30656.2,...,0.041562,-35.910457,35.772438,0.000000,-100.000000,-3077.126471,31838.077635,-8.904281,-4.132517,-21.184721
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344

6it [00:01,  3.55it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344
127,19961204,000010,26443,26661,25831,25831,114947,3010894600,-3.90,27561.8,...,0.000000,-48.285700,30.338011,0.000000,-100.000000,-4190.088235,27629.006809,-19.040306,-6.007740,35.084937
128,19961205,000010,25831,26618,25394,26224,81474,2138908300,1.52,27107.2,...,0.205638,-49.596656,33.475376,11.650758,-88.349242,-4319.752941,27300.289142,-16.667196,-6.285038,38.593890
129,19961206,000010,26443,27098,24913,24913,116347,2995709500,-5.00,26407.8,...,0.041689,-51.905515,28.764844,0.000000,-100.000000,-4633.055882,26716.092917,-19.150386,-6.815319,44.246628

7it [00:01,  3.44it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344
127,19961204,000010,26443,26661,25831,25831,114947,3010894600,-3.90,27561.8,...,0.000000,-48.285700,30.338011,0.000000,-100.000000,-4190.088235,27629.006809,-19.040306,-6.007740,35.084937
128,19961205,000010,25831,26618,25394,26224,81474,2138908300,1.52,27107.2,...,0.205638,-49.596656,33.475376,11.650758,-88.349242,-4319.752941,27300.289142,-16.667196,-6.285038,38.593890
129,19961206,000010,26443,27098,24913,24913,116347,2995709500,-5.00,26407.8,...,0.041689,-51.905515,28.764844,0.000000,-100.000000,-4633.055882,26716.092917,-19.150386,-6.815319,44.246628
130,19961207,000010,25350,25787,25350,25569,99311,2529770500,2.63,25883.4,...,0.469681,-51.733315,27.473997,9.682657,-90.317343,-4888.926471,26476.317167,-14.846638,-6.986947,44.471683
131,19961209,000010,25831,26530,25350,25350,187004,4829544300,-0.85,25577.4,...,0.518486,-51.803448,25.057531,7.405524,-92.594476,-4914.329412,26233.264213,-12.781696,-7.118298,51.187343
132,19961210,000010,25438,27098,25350,26661,66687,1743489800,5.17,25743.4,...,1.000000,-48.114751,31.681519,32.783196,-67.216804,-4661.611765,26264.483418,-9.629856,-6.768226,44.340891

8it [00:02,  3.30it/s]

KeyboardInterrupt: