In [ ]:
# ref
# tqdm
# https://mallangworld.tistory.com/entry/tqdm-%EC%9D%B4%EB%9E%80-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%83%81%ED%83%9C-%EB%B0%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC

# Library

In [1]:
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import os
import FinanceDataReader as fdr

import datetime as dt

import numpy as np

from tqdm import tqdm #진행바

#경고 에러 무시
import warnings
warnings.filterwarnings('ignore')

# GPU

In [2]:
import tensorflow as tf

#https://www.tensorflow.org/guide/gpu#allowing_gpu_memory_growth
#프로세스의 요구량만큼 메모리 사용 설정
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
if gpus:
    try:
        for i in range(len(gpus)):
            tf.config.experimental.set_memory_growth(gpus[i], True)
    except RuntimeError as e:
        # 프로그램 시작시에 메모리 증가가 설정되어야만 합니다
        print(e)
        
#지정해서 쓰고 싶으면 model 쓸 때는 with 구문 안에 넣기

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [3]:
# 확인 cell

# 왜 Code set값이 다른가에 대하여...
# d-9가 있어야하므로... d-9를 못만드는 앞의 8개는 없애야지..... 바보... 멍청...
# [8:]슬라이싱해서 index기준으로 8번째부터 쓰기

set(천억[['Code','Date']][천억['Code']==50120]['Date'].unique()) - set(ans[['Code','Date']][ans['Code']==50120]['Date'].unique())

# 얜 달라야함. (x에서 뽑은게 아님을 증명하기 위해서는.)
set(x[['Code','Date']][x['Code']==50120]['Date'].unique()) - set(천억[['Code','Date']][천억['Code']==50120]['Date'].unique())

# 천억[['Code','Date']][천억['Code']==50120]['Date'].nunique()
# 천억[['Code','Date']][천억['Code']==50120]['Date'].unique()
# ans[['Code','Date']][ans['Code']==50120]['Date'].nunique()
# ans[['Code','Date']][ans['Code']==50120]['Date'].unique()
# 천억[['Code','Date', 'Trading_Value']][천억['Code']==50120][천억['Date']=='2018-01-12']
# 천억[['Code','Date', 'Trading_Value']][천억['Code']==50120][천억['Date']=='2018-01-15']
tmp_l = []
for i in 천억[['Code','Date']][천억['Code']==50120]['Date'].unique():
    _ = tmp_l.append(천억[['Code','Date', 'Trading_Value']][천억['Code']==50120][천억['Date']==i]['Trading_Value'].values[0])
# tmp_l

tmp_l_arr = np.array(tmp_l)
np.argmax(tmp_l_arr)
np.argmin(tmp_l_arr)
len(tmp_l)

NameError: name '천억' is not defined

In [32]:
ans = pd.read_csv('stock_2018_10days.csv')
ans
ans[['Code','Date']][ans['Code']==50120]['Date'].unique()

,Code,Date,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,...,D0_TSI,D0_UO,D0_SR,D0_WR,D0_AO,D0_KAMA,D0_ROC,D0_PPO,D0_PVO,Next_change
0,50120,2018-01-15,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,29.3225,45.3787,63.9228,-36.07720,3645.880000,11858.8,68.67470,12.32460,38.8520,-0.068182
1,50120,2018-01-16,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,28.0689,45.6406,53.2520,-46.74800,3980.740000,11947.6,47.78580,12.29020,30.6275,-0.188153
2,50120,2018-01-17,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,22.3139,41.0354,25.8130,-74.18700,3687.650000,11946.2,13.10680,10.44330,23.7000,0.047210
3,50120,2018-01-18,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,18.8794,41.3833,28.8725,-71.12750,2987.650000,11947.9,3.38983,9.22399,17.4172,0.012295
4,50120,2018-01-19,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,16.5383,33.5502,25.0000,-75.00000,2637.350000,11949.9,5.10638,8.26069,12.6972,0.137652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532,11760,2018-05-15,21400,24100,20800,22400,1488904,33351449600,0.095354,20830.0,...,56.6722,68.0251,84.6369,-15.36310,6866.910000,27722.5,74.93730,13.01120,68.4751,-0.097421
2533,11760,2018-05-17,23500,23850,21950,22350,489326,10936436100,-0.064854,22040.0,...,54.5403,64.0099,85.1942,-14.80580,10338.970588,29517.6,83.12960,15.48880,67.1178,0.028037
2534,11760,2018-06-07,41650,41900,37000,38800,1305256,50643932800,-0.058252,39190.0,...,29.5457,49.8274,70.6329,-29.36710,10088.100000,36598.8,11.81820,13.02900,17.8270,-0.001161
2535,11760,2018-06-11,40500,41300,40050,41300,712521,29427117300,0.298742,38620.0,...,31.8637,53.8917,95.8333,-4.16667,10979.700000,39093.7,20.87380,13.90680,19.4140,-0.038153
2536,11760,2018-06-12,42650,44650,39500,40700,2115221,86089494700,-0.014528,38760.0,...,32.4200,52.7160,75.5020,-24.49800,12323.800000,39605.8,23.45360,14.10110,25.2156,-0.155532

array(['2018-01-15', '2018-01-16', '2018-01-17', '2018-01-18',
       '2018-01-19', '2018-01-22', '2018-01-23', '2018-01-24',
       '2018-01-25', '2018-01-26', '2018-01-29', '2018-01-30',
       '2018-01-31', '2018-02-01', '2018-02-02', '2018-02-05',
       '2018-02-06', '2018-02-07', '2018-02-12', '2018-02-19',
       '2018-02-21', '2018-02-26', '2018-04-10', '2018-04-17',
       '2018-04-18', '2018-04-19', '2018-04-20', '2018-04-24',
       '2018-04-25', '2018-05-03'], dtype=object)

# Data Load

In [5]:
data = pd.read_csv('stock_2018.csv')
data

,Index,Code,Date,Open,High,Low,Close,Volume,Trading_Value,Change,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
0,243,50120,2018-01-02,10250,12050,10150,11800,26086769,307823874200,0.145631,...,0.617452,22.3595,45.6450,73.6842,-26.3158,1259.470,9897.76,44.78530,6.24021,42.05600
1,244,50120,2018-01-03,11950,12450,10900,11750,20460474,240410569500,-0.004237,...,0.606881,24.6104,44.5857,72.7096,-27.2904,1435.350,10067.00,44.17180,7.16213,36.42410
2,245,50120,2018-01-04,11850,14150,11600,12600,60663854,764364560400,0.072340,...,0.691669,27.8890,46.0102,74.7145,-25.2855,1988.650,10221.40,53.09840,8.40391,42.40620
3,246,50120,2018-01-05,12800,13200,12000,12200,13935258,170010147600,-0.031746,...,0.605418,28.9426,46.8657,67.9276,-32.0724,2473.210,10308.60,51.17720,8.92074,34.04080
4,247,50120,2018-01-08,12450,13400,12350,12850,16471707,211661434950,0.053279,...,0.670468,30.8389,48.7672,78.6184,-21.3816,2793.380,10359.80,26.60100,9.65555,27.63640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380584,1913939,540,2018-12-21,4480,4480,4330,4480,109164,489054720,0.000000,...,0.000000,-48.1839,40.9134,21.4286,-78.5714,-363.397,4592.44,-10.31030,-3.14961,2.96624
380585,1913940,540,2018-12-24,4480,4530,4440,4520,36973,167117960,0.008929,...,0.250801,-48.6931,47.1329,27.1429,-72.8571,-394.015,4580.40,-8.87097,-3.21322,3.55599
380586,1913941,540,2018-12-26,4515,4515,4275,4470,28747,128499090,-0.011062,...,0.177769,-49.7125,54.1570,27.2727,-72.7273,-422.632,4560.38,-7.83505,-3.31474,2.02404
380587,1913942,540,2018-12-27,4475,4500,4410,4470,20617,92157990,0.000000,...,0.291459,-50.5188,54.6350,28.4672,-71.5328,-430.515,4538.92,-6.58307,-3.35971,-1.25023
380588,1913943,540,2018-12-28,4500,4825,4440,4705,60012,282356460,0.052573,...,1.000000,-42.8563,62.2204,73.5043,-26.4957,-402.265,4540.78,-1.36268,-2.95350,5.69357

# data processing

In [6]:
data = data.drop('Index', axis=1)

In [7]:
data.iloc[:,0].nunique() #1561

1561

In [8]:
col_arr = data.columns.values
col_arr

# 설명 idx 필요 없음, 식별변수 필요해서 0번째 열부터 써야함.
목적_idx = np.where(col_arr == 'Next_Change')[0][0] # 목적변수 열 idx

x = pd.concat([data.iloc[:, 0:목적_idx], data.iloc[:,목적_idx+1:]], axis = 1)
y = pd.concat([data.iloc[:, 0:2], data[['Next_Change']]], axis = 1)

array(['Code', 'Date', 'Open', 'High', 'Low', 'Close', 'Volume',
       'Trading_Value', 'Change', 'Next_Change', 'MA5', 'MA20', 'MA60',
       'MA120', 'MFI', 'ADI', 'OBV', 'CMF', 'FI', 'EOM_EMV', 'VPT', 'NVI',
       'VMAP', 'ATR', 'BHB', 'BLB', 'KCH', 'KCL', 'KCM', 'DCH', 'DCL',
       'DCM', 'UI', 'SMA', 'EMA', 'WMA', 'MACD', 'ADX', '-VI', '+VI',
       'TRIX', 'MI', 'CCI', 'DPO', 'KST', 'Ichimoku', 'Parabolic_SAR',
       'STC', 'RSI', 'SRSI', 'TSI', 'UO', 'SR', 'WR', 'AO', 'KAMA', 'ROC',
       'PPO', 'PVO'], dtype=object)

In [9]:
# (x[['Trading_Value']] >= 1000_0000_0000).sum() #2682
천억 = x[x['Trading_Value'] >= 1000_0000_0000]
천억

,Code,Date,Open,High,Low,Close,Volume,Trading_Value,Change,MA5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
0,50120,2018-01-02,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,0.617452,22.3595,45.6450,73.6842,-26.31580,1259.470000,9897.76,44.7853,6.24021,42.0560
1,50120,2018-01-03,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,0.606881,24.6104,44.5857,72.7096,-27.29040,1435.350000,10067.00,44.1718,7.16213,36.4241
2,50120,2018-01-04,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,0.691669,27.8890,46.0102,74.7145,-25.28550,1988.650000,10221.40,53.0984,8.40391,42.4062
3,50120,2018-01-05,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,0.605418,28.9426,46.8657,67.9276,-32.07240,2473.210000,10308.60,51.1772,8.92074,34.0408
4,50120,2018-01-08,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,0.670468,30.8389,48.7672,78.6184,-21.38160,2793.380000,10359.80,26.6010,9.65555,27.6364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379703,11760,2018-05-15,37200,37650,32800,34900,5016135,175063111500,0.017493,28170.0,...,1.000000,56.6722,68.0251,84.6369,-15.36310,6866.910000,27722.50,74.9373,13.01120,68.4751
379705,11760,2018-05-17,31500,40500,31250,37450,5915483,221534838350,0.188889,32910.0,...,0.655948,54.5403,64.0099,85.1942,-14.80580,10338.970588,29517.60,83.1296,15.48880,67.1178
379718,11760,2018-06-07,40650,48850,39800,43050,3703167,159421339350,0.025000,39550.0,...,0.345497,29.5457,49.8274,70.6329,-29.36710,10088.100000,36598.80,11.8182,13.02900,17.8270
379720,11760,2018-06-11,43000,50700,43000,49800,2493620,124182276000,0.158140,42770.0,...,0.598488,31.8637,53.8917,95.8333,-4.16667,10979.700000,39093.70,20.8738,13.90680,19.4140
379721,11760,2018-06-12,48700,54000,43000,47900,3781875,181151812500,-0.038153,45150.0,...,0.449870,32.4200,52.7160,75.5020,-24.49800,12323.800000,39605.80,23.4536,14.10110,25.2156

In [10]:
천억['Date'].nunique() #244

# 애초에 이부분이 틀린듯, 날짜만 부르면 안됐던 것임. 코드랑 짝지어줄 것.
need_date = list(np.sort(천억['Date'].unique())) # 날짜 list
# need_date


# 천억[['Code','Date']]
# 코드랑 날짜 같이 부르기
# cnt = 6

cd_dt_dic = {}
for i in range(len(천억[['Code','Date']])):
#     i
    tmp = 천억[['Code','Date']].iloc[[i]]
    tmp_cd = tmp['Code'].values[0]
    tmp_dt = tmp['Date'].values[0]
    #사전에 key가 이미 있으면 해당 키의 val list에 값 append하기 # 뭔가 함수가 있을 줄 알았는데 없었다. update는 key에 매치된 val값을 새로 바꾸는거..
#     if i == cnt:
#         break
    if tmp_cd not in cd_dt_dic:
        globals()[f'data_{tmp_cd}'] = [tmp['Date'].values[0]]
        cd_dt_dic[tmp_cd] = globals()[f'data_{tmp_cd}']
    else:
#         cd_dt_dic, '#'
#         globals()[f'data_{tmp_cd}']
        globals()[f'data_{tmp_cd}'].append(tmp['Date'].values[0])
        cd_dt_dic[tmp_cd] = globals()[f'data_{tmp_cd}']
#         cd_dt_dic
#     break
cd_dt_dic

244

{50120: ['2018-01-02',
  '2018-01-03',
  '2018-01-04',
  '2018-01-05',
  '2018-01-08',
  '2018-01-10',
  '2018-01-11',
  '2018-01-12',
  '2018-01-15',
  '2018-01-16',
  '2018-01-17',
  '2018-01-18',
  '2018-01-19',
  '2018-01-22',
  '2018-01-23',
  '2018-01-24',
  '2018-01-25',
  '2018-01-26',
  '2018-01-29',
  '2018-01-30',
  '2018-01-31',
  '2018-02-01',
  '2018-02-02',
  '2018-02-05',
  '2018-02-06',
  '2018-02-07',
  '2018-02-12',
  '2018-02-19',
  '2018-02-21',
  '2018-02-26',
  '2018-04-10',
  '2018-04-17',
  '2018-04-18',
  '2018-04-19',
  '2018-04-20',
  '2018-04-24',
  '2018-04-25',
  '2018-05-03'],
 67290: ['2018-04-11', '2018-04-12'],
 36120: ['2018-01-23', '2018-01-24', '2018-01-25'],
 78130: ['2018-01-11',
  '2018-04-17',
  '2018-05-18',
  '2018-05-21',
  '2018-06-21',
  '2018-06-25',
  '2018-12-18'],
 95660: ['2018-01-24', '2018-05-31'],
 7390: ['2018-01-05',
  '2018-01-16',
  '2018-01-18',
  '2018-01-19',
  '2018-01-22',
  '2018-01-24',
  '2018-01-25',
  '2018-02-05',
  '2018-02-07',
  '2018-02-08',
  '2018-02-09',
  '2018-03-07',
  '2018-03-12',
  '2018-03-13',
  '2018-03-14',
  '2018-03-16',
  '2018-03-19',
  '2018-03-20',
  '2018-03-21',
  '2018-03-22',
  '2018-03-23',
  '2018-03-26',
  '2018-03-27',
  '2018-03-28',
  '2018-03-29',
  '2018-03-30',
  '2018-04-03',
  '2018-04-11',
  '2018-04-12',
  '2018-04-13',
  '2018-04-16',
  '2018-04-17',
  '2018-04-18',
  '2018-04-19',
  '2018-04-20',
  '2018-04-23',
  '2018-04-24',
  '2018-04-25',
  '2018-04-30',
  '2018-05-09',
  '2018-05-11',
  '2018-05-25',
  '2018-06-14',
  '2018-06-15',
  '2018-06-20',
  '2018-07-19',
  '2018-07-20',
  '2018-08-03',
  '2018-08-06',
  '2018-08-07',
  '2018-09-05',
  '2018-09-06',
  '2018-09-07',
  '2018-09-10',
  '2018-09-11',
  '2018-09-12',
  '2018-09-14',
  '2018-09-17',
  '2018-09-18',
  '2018-09-19',
  '2018-09-20',
  '2018-09-28',
  '2018-10-05',
  '2018-10-15',
  '2018-11-01'],
 203650: ['2018-01-18', '2018-04-16'],
 196490: ['2018-11-01', '2018-11-27'],
 78160: ['2018-03-21'],
 68940: ['2018-01-22'],
 21080: ['2018-01-03',
  '2018-01-05',
  '2018-01-08',
  '2018-01-09',
  '2018-01-10',
  '2018-01-19',
  '2018-01-29',
  '2018-01-30',
  '2018-01-31',
  '2018-02-01',
  '2018-02-02',
  '2018-02-07',
  '2018-02-13'],
 101400: ['2018-03-15', '2018-04-17', '2018-04-27'],
 49480: ['2018-01-18'],
 65950: ['2018-04-27',
  '2018-04-30',
  '2018-05-15',
  '2018-06-05',
  '2018-06-11',
  '2018-06-12',
  '2018-06-14'],
 36090: ['2018-01-04', '2018-01-08', '2018-01-30', '2018-01-31', '2018-02-01'],
 52300: ['2018-05-16', '2018-05-17', '2018-06-11'],
 42040: ['2018-03-30', '2018-04-10', '2018-04-11', '2018-04-16'],
 82660: ['2018-06-19', '2018-06-21', '2018-10-05'],
 102940: ['2018-11-19', '2018-11-20'],
 200230: ['2018-01-03',
  '2018-01-05',
  '2018-01-09',
  '2018-01-18',
  '2018-02-02',
  '2018-03-13',
  '2018-03-16',
  '2018-03-19',
  '2018-03-26',
  '2018-03-27',
  '2018-03-28',
  '2018-03-29',
  '2018-03-30',
  '2018-04-02',
  '2018-04-03',
  '2018-04-10',
  '2018-05-09',
  '2018-05-18',
  '2018-10-19',
  '2018-11-06'],
 203690: ['2018-04-06',
  '2018-04-09',
  '2018-04-10',
  '2018-04-11',
  '2018-05-24',
  '2018-08-07'],
 48410: ['2018-09-14', '2018-09-17', '2018-09-18'],
 39610: ['2018-06-14', '2018-09-03'],
 90710: ['2018-07-16'],
 67630: ['2018-04-11'],
 14200: ['2018-04-20'],
 91590: ['2018-04-20'],
 104040: ['2018-05-24', '2018-05-29'],
 45390: ['2018-04-04',
  '2018-04-19',
  '2018-04-27',
  '2018-05-02',
  '2018-05-03',
  '2018-05-04',
  '2018-05-08',
  '2018-05-09',
  '2018-05-10',
  '2018-05-11',
  '2018-05-14',
  '2018-05-15',
  '2018-05-16',
  '2018-05-17',
  '2018-05-18',
  '2018-05-23',
  '2018-05-24',
  '2018-05-25',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-06-01',
  '2018-06-04',
  '2018-06-05',
  '2018-06-07',
  '2018-06-08',
  '2018-06-11',
  '2018-06-12',
  '2018-06-14',
  '2018-06-15',
  '2018-06-18',
  '2018-06-19',
  '2018-06-20',
  '2018-06-21',
  '2018-06-22',
  '2018-06-25',
  '2018-06-26',
  '2018-06-27',
  '2018-06-28',
  '2018-06-29',
  '2018-07-03',
  '2018-07-06',
  '2018-07-09',
  '2018-07-11',
  '2018-07-24',
  '2018-07-25',
  '2018-07-26',
  '2018-08-10',
  '2018-08-13',
  '2018-08-14',
  '2018-08-16',
  '2018-08-17',
  '2018-08-23',
  '2018-08-27',
  '2018-09-06',
  '2018-09-10',
  '2018-09-17',
  '2018-09-18',
  '2018-09-19',
  '2018-09-20',
  '2018-10-30',
  '2018-11-23',
  '2018-11-26',
  '2018-12-07',
  '2018-12-13',
  '2018-12-21'],
 85370: ['2018-03-15'],
 220630: ['2018-06-28'],
 133750: ['2018-05-25', '2018-06-01'],
 65650: ['2018-04-13', '2018-04-16', '2018-07-20'],
 59210: ['2018-04-16', '2018-04-17'],
 38500: ['2018-05-14'],
 17510: ['2018-05-17', '2018-05-18', '2018-05-29'],
 101390: ['2018-08-09'],
 52420: ['2018-01-02',
  '2018-01-03',
  '2018-01-04',
  '2018-01-05',
  '2018-01-08',
  '2018-01-09',
  '2018-01-10',
  '2018-01-11',
  '2018-01-12',
  '2018-01-15',
  '2018-01-17',
  '2018-01-19',
  '2018-02-01',
  '2018-02-02'],
 66590: ['2018-03-12', '2018-03-13', '2018-04-18'],
 48530: ['2018-11-20'],
 23440: ['2018-07-18', '2018-07-19'],
 114120: ['2018-01-11',
  '2018-01-12',
  '2018-01-23',
  '2018-01-29',
  '2018-01-31',
  '2018-02-01',
  '2018-02-21',
  '2018-02-22',
  '2018-02-23',
  '2018-02-26',
  '2018-02-27',
  '2018-02-28',
  '2018-03-02',
  '2018-03-05',
  '2018-03-06',
  '2018-03-12',
  '2018-03-13',
  '2018-03-14',
  '2018-03-29',
  '2018-04-16',
  '2018-04-26'],
 191420: ['2018-07-30'],
 66700: ['2018-03-21', '2018-04-26', '2018-05-18'],
 53300: ['2018-01-17', '2018-01-18'],
 184230: ['2018-02-05', '2018-02-06'],
 14570: ['2018-02-06', '2018-02-07', '2018-02-09', '2018-09-28'],
 90360: ['2018-05-30', '2018-06-28'],
 36630: ['2018-05-03'],
 97780: ['2018-04-16',
  '2018-04-17',
  '2018-04-18',
  '2018-04-27',
  '2018-05-02',
  '2018-07-03',
  '2018-07-04'],
 69080: ['2018-01-04', '2018-01-05', '2018-03-21'],
 24810: ['2018-01-02',
  '2018-01-03',
  '2018-01-04',
  '2018-01-05',
  '2018-01-08',
  '2018-01-09',
  '2018-01-10',
  '2018-03-05',
  '2018-03-07',
  '2018-03-08',
  '2018-03-09',
  '2018-03-12',
  '2018-03-19',
  '2018-03-28',
  '2018-03-29',
  '2018-04-06',
  '2018-04-18',
  '2018-04-19',
  '2018-04-20',
  '2018-04-23',
  '2018-04-24',
  '2018-04-25',
  '2018-04-26',
  '2018-04-27',
  '2018-04-30',
  '2018-05-02',
  '2018-05-03',
  '2018-05-04',
  '2018-05-08',
  '2018-05-09',
  '2018-05-10',
  '2018-05-11',
  '2018-05-14',
  '2018-05-15',
  '2018-05-16',
  '2018-05-17',
  '2018-05-24',
  '2018-05-25',
  '2018-05-28',
  '2018-05-29',
  '2018-05-30',
  '2018-06-01',
  '2018-06-12',
  '2018-09-06',
  '2018-12-24'],
 49630: ['2018-03-08', '2018-04-18', '2018-04-19'],
 47820: ['2018-11-08'],
 224060: ['2018-04-03', '2018-04-10', '2018-04-11', '2018-05-21'],
 99220: ['2018-05-03'],
 6920: ['2018-02-20'],
 53030: ['2018-04-09', '2018-04-11'],
 86040: ['2018-01-17'],
 250: ['2018-01-11', '2018-02-20', '2018-02-21', '2018-04-06'],
 222080: ['2018-02-26', '2018-03-14', '2018-06-25'],
 46120: ['2018-04-20',
  '2018-04-27',
  '2018-04-30',
  '2018-05-23',
  '2018-05-24',
  '2018-06-12'],
 33100: ['2018-03-08',
  '2018-03-09',
  '2018-03-28',
  '2018-03-29',
  '2018-04-13',
  '2018-04-17',
  '2018-04-18',
  '2018-04-19',
  '2018-09-06'],
 65060: ['2018-01-11', '2018-12-19'],
 192250: ['2018-01-25'],
 217600: ['2018-03-30'],
 29960: ['2018-10-10'],
 34230: ['2018-01-17', '2018-04-02', '2018-04-03'],
 28300: ['2018-03-23',
  '2018-03-26',
  '2018-03-28',
  '2018-04-04',
  '2018-04-06',
  '2018-04-09',
  '2018-04-10',
  '2018-05-09',
  '2018-05-10',
  '2018-05-25',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-06-04',
  '2018-06-05',
  '2018-06-12',
  '2018-08-09',
  '2018-08-14',
  '2018-10-12'],
 47920: ['2018-02-05', '2018-02-14'],
 38290: ['2018-01-18', '2018-01-23', '2018-01-24'],
 225530: ['2018-06-04'],
 78860: ['2018-04-24', '2018-04-25'],
 53800: ['2018-02-20',
  '2018-02-21',
  '2018-02-22',
  '2018-03-06',
  '2018-03-29',
  '2018-03-30'],
 193250: ['2018-05-25', '2018-05-28', '2018-05-29', '2018-05-30'],
 11320: ['2018-12-18'],
 1840: ['2018-03-09', '2018-03-23', '2018-04-19', '2018-04-20', '2018-04-23'],
 68330: ['2018-04-10'],
 41460: ['2018-01-18'],
 64240: ['2018-03-22'],
 214270: ['2018-02-09'],
 35900: ['2018-01-17', '2018-05-02', '2018-10-24', '2018-10-26'],
 33640: ['2018-06-19', '2018-06-20'],
 60570: ['2018-01-31', '2018-02-22', '2018-05-29', '2018-05-30'],
 90460: ['2018-01-18'],
 65450: ['2018-05-16', '2018-05-17', '2018-05-25'],
 38070: ['2018-04-10'],
 71670: ['2018-01-09'],
 61970: ['2018-05-25',
  '2018-05-28',
  '2018-06-01',
  '2018-06-04',
  '2018-06-05',
  '2018-07-31',
  '2018-08-01',
  '2018-08-03',
  '2018-08-14',
  '2018-08-16',
  '2018-09-04',
  '2018-09-05',
  '2018-12-18'],
 95190: ['2018-04-19'],
 95700: ['2018-01-11', '2018-01-12', '2018-01-15'],
 166480: ['2018-03-27', '2018-04-10', '2018-04-13'],
 54780: ['2018-02-02',
  '2018-03-13',
  '2018-03-14',
  '2018-03-15',
  '2018-03-16',
  '2018-03-20',
  '2018-04-09',
  '2018-05-25',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-06-01',
  '2018-06-04',
  '2018-06-05',
  '2018-06-07',
  '2018-07-05',
  '2018-07-31',
  '2018-08-01',
  '2018-08-13',
  '2018-08-14',
  '2018-08-16',
  '2018-08-20',
  '2018-08-21',
  '2018-08-22',
  '2018-08-23',
  '2018-08-24',
  '2018-08-27',
  '2018-08-28',
  '2018-08-29',
  '2018-08-30',
  '2018-08-31',
  '2018-09-03',
  '2018-09-04',
  '2018-09-05',
  '2018-09-06',
  '2018-09-07',
  '2018-09-10',
  '2018-09-11',
  '2018-09-12',
  '2018-09-19',
  '2018-09-21',
  '2018-09-28',
  '2018-10-01',
  '2018-10-02',
  '2018-10-08',
  '2018-10-10',
  '2018-10-11',
  '2018-10-12',
  '2018-10-15',
  '2018-10-17',
  '2018-10-18',
  '2018-10-19',
  '2018-10-22',
  '2018-10-23',
  '2018-10-24',
  '2018-10-25',
  '2018-10-30',
  '2018-10-31',
  '2018-11-02',
  '2018-11-09',
  '2018-11-12',
  '2018-11-13',
  '2018-11-14'],
 58820: ['2018-01-02',
  '2018-01-03',
  '2018-01-05',
  '2018-01-12',
  '2018-01-18',
  '2018-01-24',
  '2018-01-25',
  '2018-03-15',
  '2018-03-23',
  '2018-03-27',
  '2018-09-20'],
 114450: ['2018-03-16', '2018-09-19'],
 19550: ['2018-01-08',
  '2018-02-01',
  '2018-02-02',
  '2018-02-05',
  '2018-02-07',
  '2018-02-13'],
 68240: ['2018-04-30'],
 27830: ['2018-01-05', '2018-01-30', '2018-02-01', '2018-02-02'],
 92600: ['2018-08-03', '2018-08-08'],
 52020: ['2018-02-19', '2018-09-19'],
 86520: ['2018-01-16', '2018-10-23', '2018-11-01'],
 32820: ['2018-04-27',
  '2018-04-30',
  '2018-05-03',
  '2018-05-08',
  '2018-05-10',
  '2018-07-27'],
 41190: ['2018-01-02',
  '2018-01-03',
  '2018-01-05',
  '2018-01-09',
  '2018-01-10',
  '2018-01-11',
  '2018-01-12',
  '2018-01-15',
  '2018-01-16',
  '2018-01-17',
  '2018-01-18',
  '2018-01-19',
  '2018-01-22',
  '2018-01-23',
  '2018-01-24',
  '2018-01-25',
  '2018-01-29',
  '2018-01-30',
  '2018-02-01',
  '2018-02-07',
  '2018-02-21',
  '2018-04-24',
  '2018-04-25',
  '2018-04-27',
  '2018-07-17',
  '2018-07-18',
  '2018-07-20',
  '2018-07-25',
  '2018-08-22'],
 23410: ['2018-05-28'],
 147830: ['2018-03-08', '2018-03-28'],
 204840: ['2018-06-08'],
 36170: ['2018-01-11', '2018-01-26', '2018-01-29', '2018-01-31'],
 84990: ['2018-01-12',
  '2018-01-15',
  '2018-01-16',
  '2018-01-17',
  '2018-01-18',
  '2018-01-19',
  '2018-01-22',
  '2018-01-23',
  '2018-01-24',
  '2018-01-25',
  '2018-01-26',
  '2018-01-29',
  '2018-01-30',
  '2018-01-31',
  '2018-02-01',
  '2018-02-02',
  '2018-02-05',
  '2018-02-06',
  '2018-02-07',
  '2018-02-08',
  '2018-02-09',
  '2018-02-12',
  '2018-02-13',
  '2018-02-28',
  '2018-03-23',
  '2018-04-04',
  '2018-04-09',
  '2018-04-10',
  '2018-04-12',
  '2018-05-23',
  '2018-05-24',
  '2018-05-25',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-07-05',
  '2018-09-20',
  '2018-12-26',
  '2018-12-27'],
 48470: ['2018-09-05'],
 66410: ['2018-03-08',
  '2018-04-18',
  '2018-05-17',
  '2018-05-18',
  '2018-05-23',
  '2018-05-24',
  '2018-05-28',
  '2018-05-31',
  '2018-06-19',
  '2018-06-20',
  '2018-06-22',
  '2018-07-03'],
 6910: ['2018-02-22', '2018-04-20', '2018-04-23', '2018-05-03'],
 35890: ['2018-06-12', '2018-06-14', '2018-06-15', '2018-07-30', '2018-07-31'],
 68760: ['2018-01-03',
  '2018-01-04',
  '2018-01-08',
  '2018-01-09',
  '2018-01-11',
  '2018-01-12',
  '2018-01-15',
  '2018-01-16',
  '2018-01-17',
  '2018-01-18',
  '2018-01-19',
  '2018-01-22',
  '2018-01-23',
  '2018-01-24',
  '2018-01-29',
  '2018-01-30',
  '2018-02-08',
  '2018-04-05',
  '2018-04-09',
  '2018-05-31',
  '2018-11-16',
  '2018-11-19'],
 25980: ['2018-05-17',
  '2018-05-21',
  '2018-06-01',
  '2018-06-18',
  '2018-06-19',
  '2018-06-20',
  '2018-09-21',
  '2018-10-04',
  '2018-12-11',
  '2018-12-12',
  '2018-12-13',
  '2018-12-14',
  '2018-12-17',
  '2018-12-18',
  '2018-12-24',
  '2018-12-26',
  '2018-12-27',
  '2018-12-28'],
 119830: ['2018-06-20'],
 109610: ['2018-04-20'],
 39200: ['2018-04-04', '2018-11-05', '2018-11-06'],
 215380: ['2018-03-22',
  '2018-03-23',
  '2018-04-10',
  '2018-05-16',
  '2018-05-17'],
 14190: ['2018-08-31'],
 43910: ['2018-05-04'],
 7370: ['2018-02-09'],
 85660: ['2018-01-02',
  '2018-01-03',
  '2018-01-04',
  '2018-01-05',
  '2018-01-08',
  '2018-01-09',
  '2018-01-10',
  '2018-01-12',
  '2018-01-16',
  '2018-01-17',
  '2018-01-19',
  '2018-01-26',
  '2018-02-01',
  '2018-02-02',
  '2018-02-06',
  '2018-02-07',
  '2018-02-08',
  '2018-02-09',
  '2018-02-12',
  '2018-02-20',
  '2018-02-26',
  '2018-03-08',
  '2018-03-12',
  '2018-03-14',
  '2018-03-16',
  '2018-03-19',
  '2018-03-20',
  '2018-03-21',
  '2018-03-22',
  '2018-03-26',
  '2018-03-27',
  '2018-03-28',
  '2018-03-30',
  '2018-04-02',
  '2018-04-05',
  '2018-04-06',
  '2018-04-12',
  '2018-04-18',
  '2018-09-20'],
 39420: ['2018-01-15', '2018-01-17'],
 81150: ['2018-05-08', '2018-09-13'],
 9520: ['2018-04-25',
  '2018-04-26',
  '2018-06-07',
  '2018-09-10',
  '2018-09-11',
  '2018-09-18',
  '2018-09-19',
  '2018-09-27'],
 94940: ['2018-05-17',
  '2018-05-23',
  '2018-05-29',
  '2018-05-30',
  '2018-08-10',
  '2018-09-04',
  '2018-09-19'],
 32860: ['2018-01-31', '2018-06-22', '2018-06-25', '2018-06-28', '2018-08-20'],
 210: ['2018-01-26', '2018-08-08'],
 11200: ['2018-01-02',
  '2018-04-05',
  '2018-04-06',
  '2018-04-23',
  '2018-04-30',
  '2018-05-02',
  '2018-05-14',
  '2018-05-15',
  '2018-05-16',
  '2018-05-28',
  '2018-09-19'],
 92220: ['2018-05-31'],
 11070: ['2018-01-09', '2018-01-19', '2018-05-28', '2018-08-24', '2018-09-13'],
 10060: ['2018-01-04',
  '2018-01-05',
  '2018-01-10',
  '2018-01-11',
  '2018-01-24',
  '2018-02-01',
  '2018-02-06',
  '2018-03-22',
  '2018-04-25',
  '2018-06-04'],
 96770: ['2018-01-29',
  '2018-02-26',
  '2018-05-02',
  '2018-05-31',
  '2018-07-02',
  '2018-10-01'],
 2100: ['2018-06-18'],
 8350: ['2018-05-09',
  '2018-05-11',
  '2018-11-05',
  '2018-11-07',
  '2018-12-03',
  '2018-12-04',
  '2018-12-05',
  '2018-12-10',
  '2018-12-12',
  '2018-12-14'],
 47040: ['2018-01-11'],
 17180: ['2018-02-05',
  '2018-02-06',
  '2018-02-07',
  '2018-02-09',
  '2018-02-20',
  '2018-02-21',
  '2018-03-22'],
 6400: ['2018-01-05',
  '2018-01-19',
  '2018-01-22',
  '2018-01-23',
  '2018-01-24',
  '2018-01-25',
  '2018-01-31',
  '2018-02-01',
  '2018-02-02',
  '2018-02-05',
  '2018-02-06',
  '2018-02-07',
  '2018-03-09',
  '2018-03-12',
  '2018-03-14',
  '2018-03-15',
  '2018-03-16',
  '2018-03-19',
  '2018-04-02',
  '2018-05-23',
  '2018-06-04',
  '2018-06-07',
  '2018-06-12',
  '2018-06-14',
  '2018-06-15',
  '2018-06-18',
  '2018-06-19',
  '2018-06-20',
  '2018-06-29',
  '2018-07-06',
  '2018-07-12',
  '2018-07-13',
  '2018-07-25',
  '2018-07-30',
  '2018-08-10',
  '2018-09-03',
  '2018-09-11',
  '2018-09-12',
  '2018-09-13',
  '2018-09-18',
  '2018-10-05',
  '2018-10-12',
  '2018-10-23',
  '2018-10-24',
  '2018-10-25',
  '2018-10-26',
  '2018-10-29',
  '2018-10-30',
  '2018-11-01',
  '2018-11-02',
  '2018-11-08',
  '2018-11-09',
  '2018-11-13',
  '2018-11-20',
  '2018-11-21',
  '2018-12-03',
  '2018-12-13',
  '2018-12-21'],
 28050: ['2018-01-10',
  '2018-01-26',
  '2018-02-08',
  '2018-03-12',
  '2018-03-13',
  '2018-05-15',
  '2018-05-21',
  '2018-05-31',
  '2018-06-01'],
 55550: ['2018-05-31', '2018-07-26', '2018-09-14', '2018-12-13'],
 81000: ['2018-01-23'],
 1550: ['2018-06-12', '2018-06-15'],
 5490: ['2018-01-03',
  '2018-01-04',
  '2018-01-12',
  '2018-01-25',
  '2018-01-30',
  '2018-02-01',
  '2018-02-06',
  '2018-02-08',
  '2018-02-09',
  '2018-02-28',
  '2018-03-02',
  '2018-03-08',
  '2018-03-09',
  '2018-03-14',
  '2018-03-19',
  '2018-03-23',
  '2018-03-26',
  '2018-03-27',
  '2018-04-10',
  '2018-04-18',
  '2018-04-19',
  '2018-04-30',
  '2018-05-02',
  '2018-05-31',
  '2018-06-14',
  '2018-06-19',
  '2018-07-24',
  '2018-08-30',
  '2018-09-05',
  '2018-09-11',
  '2018-09-12',
  '2018-09-13',
  '2018-09-14',
  '2018-09-19',
  '2018-09-21',
  '2018-09-27',
  '2018-09-28',
  '2018-10-04',
  '2018-10-05',
  '2018-10-11',
  '2018-10-30',
  '2018-11-14',
  '2018-11-26',
  '2018-11-28',
  '2018-11-29',
  '2018-11-30',
  '2018-12-03',
  '2018-12-13'],
 9460: ['2018-10-24'],
 720: ['2018-01-29',
  '2018-03-09',
  '2018-04-19',
  '2018-04-20',
  '2018-04-23',
  '2018-04-24',
  '2018-04-25',
  '2018-04-26',
  '2018-04-27',
  '2018-04-30',
  '2018-05-02',
  '2018-05-03',
  '2018-05-04',
  '2018-05-08',
  '2018-05-09',
  '2018-05-10',
  '2018-05-11',
  '2018-05-14',
  '2018-05-15',
  '2018-05-16',
  '2018-05-17',
  '2018-05-18',
  '2018-05-21',
  '2018-05-23',
  '2018-05-24',
  '2018-05-25',
  '2018-05-28',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-06-01',
  '2018-06-04',
  '2018-06-05',
  '2018-06-07',
  '2018-06-08',
  '2018-06-11',
  '2018-06-12',
  '2018-06-14',
  '2018-06-15',
  '2018-06-18',
  '2018-06-19',
  '2018-06-20',
  '2018-06-21',
  '2018-06-22',
  '2018-06-25',
  '2018-06-26',
  '2018-06-27',
  '2018-06-28',
  '2018-06-29',
  '2018-07-02',
  '2018-07-03',
  '2018-07-05',
  '2018-07-06',
  '2018-07-09',
  '2018-07-11',
  '2018-07-24',
  '2018-07-25',
  '2018-07-26',
  '2018-08-10',
  '2018-08-13',
  '2018-08-23',
  '2018-08-27',
  '2018-09-10',
  '2018-09-11',
  '2018-09-12',
  '2018-09-19',
  '2018-09-21',
  '2018-10-10',
  '2018-10-11',
  '2018-11-07'],
 42670: ['2018-01-09', '2018-04-02', '2018-04-30'],
 17800: ['2018-03-09',
  '2018-03-28',
  '2018-04-19',
  '2018-04-20',
  '2018-04-23',
  '2018-04-30',
  '2018-05-02',
  '2018-05-09',
  '2018-05-10',
  '2018-05-11',
  '2018-05-14',
  '2018-05-15',
  '2018-05-16',
  '2018-05-17',
  '2018-05-18',
  '2018-05-23',
  '2018-05-25',
  '2018-05-28',
  '2018-05-29',
  '2018-05-30',
  '2018-05-31',
  '2018-06-01',
  '2018-06-04',
  '2018-06-05',
  '2018-06-11',
  '2018-06-12',
  '2018-06-14',
  '2018-07-24',
  '2018-08-27',
  '2018-09-19',
  '2018-09-21',
  '2018-10-04',
  '2018-10-10',
  '2018-10-11',
  '2018-11-07'],
 120: ['2018-03-16'],
 105560: ['2018-02-06',
  '2018-02-08',
  '2018-02-26',
  '2018-03-08',
  '2018-05-30',
  '2018-05-31',
  '2018-08-08',
  '2018-09-21',
  '2018-10-04',
  '2018-10-31',
  '2018-11-21',
  '2018-12-13'],
 2760: ['2018-03-27',
  '2018-04-04',
  '2018-04-05',
  '2018-04-06',
  '2018-05-21',
  '2018-05-23',
  '2018-06-26',
  '2018-06-27',
  '2018-06-29'],
 2700: ['2018-07-17', '2018-07-18'],
 19170: ['2018-10-01'],
 90430: ['2018-03-09',
  '2018-04-02',
  '2018-04-03',
  '2018-06-28',
  '2018-07-26',
  '2018-07-27',
  '2018-10-04',
  '2018-10-29',
  '2018-10-30',
  '2018-11-15',
  '2018-11-21',
  '2018-11-22',
  '2018-11-27',
  '2018-11-28',
  '2018-12-12',
  '2018-12-13'],
 36570: ['2018-01-03',
  '2018-01-04',
  '2018-01-26',
  '2018-02-08',
  '2018-05-10',
  '2018-05-11',
  '2018-11-28',
  '2018-11-29',
  '2018-12-06',
  '2018-12-13',
  '2018-12-21'],
 3520: ['2018-01-12', '2018-01-16', '2018-04-04', '2018-04-20'],
 161890: ['2018-02-21'],
 9420: ['2018-01-03',
  '2018-01-09',
  '2018-01-10',
  '2018-01-11',
  '2018-01-12',
  '2018-01-15',
  '2018-01-16',
  '2018-01-19',
  '2018-01-30',
  '2018-01-31',
  '2018-02-01',
  '2018-02-06',

In [11]:
# 이건 걍 버리는 cell

dday_alldf = pd.DataFrame()


# need_date가 아닌 cd_dt_dic에서 고르기
for k,i in tqdm(enumerate(need_date)):
    idx = x[x['Date']==i].index
#     idx.values[0]
    dday_df = pd.DataFrame([x.iloc[:,0:2].loc[idx.values[0]]])
    dday_df.rename(index = {idx.values[0] : i}, inplace = True)
    dday_df # 이거의 code와 같은 df인 거 중에서 고르기
    
    for j in range(9, -1, -1):
        
        idx

        tmp = x.iloc[idx-j].iloc[:,2:]
        tmp.columns = [f'D-{j}_{ori_col}' for ori_col in x[x['Date']==i].iloc[:,2:].columns]
        
        # index가 같아야 한 row에 들어갈 수 있음
        tmp = tmp.rename(index = {idx.values[0]-j : i})
        tmp
        dday_df = pd.concat([dday_df, tmp], axis = 1)
        break
    
    dday_df = pd.concat([dday_df, y.iloc[idx]['Next_Change'].rename(index = {idx.values[0]:i})], axis = 1)
    dday_alldf = pd.concat([dday_alldf, dday_df])
    
    break

0it [00:00, ?it/s]

             Code        Date
2018-01-02  50120  2018-01-02

Int64Index([     0,    244,    488,    732,    976,   1220,   1464,   1708,
              1952,   2196,
            ...
            378149, 378393, 378637, 378881, 379125, 379369, 379613, 379857,
            380101, 380345],
           dtype='int64', length=1560)

,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,D-9_MA20,D-9_MA60,...,D-9_SRSI,D-9_TSI,D-9_UO,D-9_SR,D-9_WR,D-9_AO,D-9_KAMA,D-9_ROC,D-9_PPO,D-9_PVO
380580,4800,4800,4660,4715,11410,53798150,-0.007368,4757.0,4945.00,5179.08,...,0.000000,-36.71270,45.2476,12.50000,-87.50000,-255.6910,4794.32,-6.44841,-2.221880,-22.396600
235,6670,6940,6650,6760,303522,2051808720,0.001481,6700.0,7344.50,7727.50,...,0.607821,-28.76380,34.0629,20.28990,-79.71010,-866.5290,6776.88,-10.81790,-4.288480,-11.574100
479,8253,8322,7860,8008,45465,364083720,-0.034366,8416.4,8735.85,9514.95,...,0.000000,-20.81080,37.9987,10.54130,-89.45870,-410.8530,8778.77,-11.78670,-2.933780,-16.304000
723,6106,6188,5915,6143,207259,1273192037,-0.002922,6197.8,6420.65,6726.48,...,0.189992,-13.18860,47.2759,26.11680,-73.88320,-222.2560,6366.68,-5.59398,-1.692870,-16.536800
967,5300,5380,5240,5370,1717,9220290,0.013208,5330.0,5261.00,5521.83,...,0.745578,-7.21810,70.5249,64.86490,-35.13510,15.8529,5289.79,2.48092,-0.466917,-16.226700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379360,35350,37200,35050,36900,153465,5662858500,0.035063,35330.0,33012.50,34779.20,...,1.000000,11.14200,62.1176,94.28570,-5.71429,2717.5000,33674.00,13.88890,1.956540,2.050140
379604,115000,118500,112500,116500,602835,70230277500,0.000000,116300.0,106145.00,111773.00,...,0.820989,19.96580,62.6200,77.67860,-22.32140,10239.7000,114499.00,16.50000,2.591040,-0.816904
379848,28700,29550,27850,29300,204592,5994545600,0.000000,28750.0,29185.00,28336.70,...,0.312954,8.49431,54.2657,41.05260,-58.94740,918.6760,29385.10,1.55979,1.585500,-6.891430
380092,16500,16600,15750,15950,162000,2583900000,-0.042042,16520.0,16822.50,22009.20,...,0.000000,-19.95460,38.0601,7.69231,-92.30770,-171.3240,17379.20,-4.49102,-3.918830,-27.803400
380336,2550,2670,2500,2660,97512,259381920,0.043137,2479.0,2317.00,2430.08,...,1.000000,20.32840,67.3440,97.08740,-2.91262,205.8240,2447.76,21.18450,2.878660,13.086600

0it [00:00, ?it/s]

In [12]:
for enu,(key, val) in enumerate(cd_dt_dic.items()):
    enu
    key
    val
    break

0

50120

['2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-08',
 '2018-01-10',
 '2018-01-11',
 '2018-01-12',
 '2018-01-15',
 '2018-01-16',
 '2018-01-17',
 '2018-01-18',
 '2018-01-19',
 '2018-01-22',
 '2018-01-23',
 '2018-01-24',
 '2018-01-25',
 '2018-01-26',
 '2018-01-29',
 '2018-01-30',
 '2018-01-31',
 '2018-02-01',
 '2018-02-02',
 '2018-02-05',
 '2018-02-06',
 '2018-02-07',
 '2018-02-12',
 '2018-02-19',
 '2018-02-21',
 '2018-02-26',
 '2018-04-10',
 '2018-04-17',
 '2018-04-18',
 '2018-04-19',
 '2018-04-20',
 '2018-04-24',
 '2018-04-25',
 '2018-05-03']

In [64]:
# 아직 완전 맞다고는 못하겠음. 두 번째 for문 할 때 val을 슬라이싱해서 val[8:]을 쓰는건 옳은 접근이 아님.


from tqdm.notebook import tqdm

dday_alldf = pd.DataFrame()


# need_date가 아닌 cd_dt_dic에서 고르기
for k,(key, val) in tqdm(enumerate(cd_dt_dic.items())):
#     key인 동안에
    for i in val[8:]:
#         i #
#         "x[x['Code']==key][x['Date']==i]" #
#         x[x['Code']==key][x['Date']==i] #
        idx = x[x['Code']==key][x['Date']==i].index
#         'idx.values[0]', idx.values[0] #
        dday_df = pd.DataFrame([x.iloc[:,0:2].loc[idx.values[0]]])
        dday_df.rename(index = {idx.values[0] : i}, inplace = True)
#         dday_df # 이거의 code와 같은 df인 거 중에서 고르기

        for j in range(9, -1, -1):

#             idx #

            tmp = x.iloc[idx-j].iloc[:,2:]
            tmp.columns = [f'D-{j}_{ori_col}' for ori_col in x.iloc[:,2:].columns]

            # index가 같아야 한 row에 들어갈 수 있음
#             idx.values[0]-j #
            tmp = tmp.rename(index = {idx.values[0]-j : i})
#             tmp #
            dday_df = pd.concat([dday_df, tmp], axis = 1)
#             break

        dday_df = pd.concat([dday_df, y.iloc[idx]['Next_Change'].rename(index = {idx.values[0]:i})], axis = 1)
        dday_alldf = pd.concat([dday_alldf, dday_df])

#         dday_alldf #

#         break
    break
dday_alldf

0it [00:00, ?it/s]

,Code,Date,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,...,D-0_TSI,D-0_UO,D-0_SR,D-0_WR,D-0_AO,D-0_KAMA,D-0_ROC,D-0_PPO,D-0_PVO,Next_Change
2018-01-15,50120,2018-01-15,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,29.322500,45.3787,63.92280,-36.07720,3645.8800,11858.800000,68.67470,12.324600,38.852000,-0.068182
2018-01-16,50120,2018-01-16,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,28.068900,45.6406,53.25200,-46.74800,3980.7400,11947.600000,47.78580,12.290200,30.627500,-0.188153
2018-01-17,50120,2018-01-17,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,22.313900,41.0354,25.81300,-74.18700,3687.6500,11946.200000,13.10680,10.443300,23.700000,0.047210
2018-01-18,50120,2018-01-18,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,18.879400,41.3833,28.87250,-71.12750,2987.6500,11947.900000,3.38983,9.223990,17.417200,0.012295
2018-01-19,50120,2018-01-19,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,16.538300,33.5502,25.00000,-75.00000,2637.3500,11949.900000,5.10638,8.260690,12.697200,0.137652
2018-01-22,50120,2018-01-22,12800,12950,11300,11700,7846263,91801277100,-0.089494,12220.0,...,16.586600,38.8732,39.13040,-60.86960,2330.7400,11975.800000,11.50790,8.478310,18.701000,0.021352
2018-01-23,50120,2018-01-23,11650,15200,11500,15200,39646571,602627879200,0.299145,12910.0,...,16.931000,38.1931,39.86930,-60.13070,2132.2100,12047.300000,17.62300,8.714070,14.064900,-0.055749
2018-01-24,50120,2018-01-24,13900,18950,11650,12950,111178326,1439759321700,-0.148026,12980.0,...,16.058200,31.2816,29.41180,-70.58820,2312.3500,12080.000000,5.44747,8.294500,7.120210,0.036900
2018-01-25,50120,2018-01-25,15300,15400,12650,13700,57595886,789063638200,0.057915,13280.0,...,15.888200,31.5119,35.94770,-64.05230,2563.8200,12113.000000,20.08550,8.167750,6.807290,0.298932
2018-01-26,50120,2018-01-26,13700,16100,13400,15400,58256770,897154258000,0.124088,13790.0,...,19.843300,48.4298,90.84970,-9.15033,3031.1800,12544.800000,20.06580,10.401400,26.161100,-0.013699
2018-01-29,50120,2018-01-29,14700,15500,14000,14350,19305022,277027065700,-0.068182,14320.0,...,22.426500,43.3164,65.98980,-34.01020,3806.6200,12747.600000,38.99610,11.738500,33.051500,-0.069444
2018-01-30,50120,2018-01-30,13050,13300,11650,11650,19903337,231873876050,-0.188153,13610.0,...,22.688800,40.1735,52.82050,-47.17950,4132.2100,12878.800000,22.26280,11.891600,25.987800,-0.002985
2018-01-31,50120,2018-01-31,12200,13150,11600,12200,18229011,222393934200,0.047210,13460.0,...,22.823000,37.5675,52.30770,-47.69230,4517.3500,13420.200000,8.44156,11.814600,21.158900,-0.011976
2018-02-01,50120,2018-02-01,12200,13750,12100,12350,20744693,256196958550,0.012295,13190.0,...,22.659300,38.9744,50.25640,-49.74360,4657.9400,13776.200000,14.98260,11.491400,14.300400,-0.060606
2018-02-02,50120,2018-02-02,12500,15450,12450,14050,63098632,886535779600,0.137652,12920.0,...,21.180000,38.7672,40.00000,-60.00000,4334.1200,13883.500000,33.04720,10.579600,6.990610,-0.064516
2018-02-05,50120,2018-02-05,14350,15300,13900,14350,23245868,333578205800,0.021352,12920.0,...,18.669000,38.2469,29.74360,-70.25640,3243.9700,13888.900000,18.85250,9.226710,-0.053288,0.017241
2018-02-06,50120,2018-02-06,14450,14800,13550,13550,10948361,148350291550,-0.055749,13300.0,...,16.885000,35.5135,32.30770,-67.69230,2319.4100,13895.800000,19.43320,8.195060,-5.180440,-0.084746
2018-02-07,50120,2018-02-07,13600,15400,13600,14050,32155164,451780054200,0.036900,13670.0,...,13.818600,34.5633,15.13510,-84.86490,1592.3500,13894.000000,-3.91459,6.632440,-8.227760,0.018519
2018-02-12,50120,2018-02-12,18200,18550,16550,16750,28291666,473885405500,-0.069444,16120.0,...,7.294420,33.1250,7.55814,-92.44190,186.1760,13605.000000,-4.62633,3.257720,-23.403200,0.026119
2018-02-19,50120,2018-02-19,16300,16850,15000,15500,12302624,190690672000,-0.060606,16690.0,...,4.944520,27.3542,18.60470,-81.39530,-226.3240,13687.975172,-14.32840,2.037190,-33.637000,-0.013937
2018-02-21,50120,2018-02-21,13700,14750,12750,14750,13510914,199285981500,0.017241,15590.0,...,5.186560,32.9620,35.65220,-64.34780,-86.3235,13724.800000,-10.30300,2.063260,-33.502300,0.000000
2018-02-26,50120,2018-02-26,13200,14500,13150,13250,6964523,92279929750,-0.036364,13950.0,...,4.253450,35.3776,46.66670,-53.33330,54.7059,13739.600000,-4.06780,1.562320,-38.818300,-0.021201
2018-04-10,50120,2018-04-10,12700,12750,11600,11750,2031262,23867328500,-0.060000,11930.0,...,-17.761100,39.8322,51.56250,-48.43750,-1430.1500,12119.300000,7.92952,-4.147200,9.597470,-0.036735
2018-04-17,50120,2018-04-17,11400,11500,10650,10700,1848128,19774969600,-0.048889,11290.0,...,-1.480640,46.0528,83.69570,-16.30430,135.7350,12493.600000,22.97870,-0.213207,42.797100,-0.100346
2018-04-18,50120,2018-04-18,10850,11400,10750,10900,1716184,18706405600,0.018692,11200.0,...,0.808038,39.1073,52.17390,-47.82610,474.2650,12531.700000,14.03510,0.344193,41.793600,-0.011539
2018-04-19,50120,2018-04-19,10900,10950,10600,10800,1092906,11803384800,-0.009174,11010.0,...,2.097040,34.3881,48.91300,-51.08700,735.2940,12550.600000,14.22220,0.676097,34.705700,0.042802
2018-04-20,50120,2018-04-20,10750,11350,10750,11150,1071724,11949722600,0.032407,10960.0,...,4.284240,36.9507,60.86960,-39.13040,995.8820,12621.100000,25.23360,1.277660,31.074800,-0.022388
2018-04-24,50120,2018-04-24,12300,12800,11800,11800,7196044,84913319200,-0.036735,11380.0,...,8.417420,44.4105,80.43480,-19.56520,1186.1800,12742.100000,32.40740,2.471100,18.323100,-0.027972
2018-04-25,50120,2018-04-25,11900,12450,11600,12050,6600737,79538880850,0.021186,11610.0,...,9.887830,42.3158,71.73910,-28.26090,1201.6200,12811.700000,24.66370,2.910690,15.216300,-0.014389
2018-05-03,50120,2018-05-03,13250,13800,12750,12850,8989837,115519405450,-0.011539,12870.0,...,9.226940,38.6561,42.42420,-57.57580,1132.5000,12920.300000,9.46502,2.526090,-6.306060,0.003759

In [59]:
np.where(x[x['Code']==50120]['Date'].values == '2018-01-15')[0][0] # D9~D0까지 일 수는 9개가 아니라 10개니까...


cnt = 10

for k,(key, val) in tqdm(enumerate(cd_dt_dic.items())):
#     key인 동안에
    for i in val:
        if k == 10:
            break
            
        elif np.where(x[x['Code']==key]['Date'].values == i)[0][0] >= 9 :
            print(i)
#             x[x['Code']==key]['Date'].values

9

0it [00:00, ?it/s]

2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-12
2018-02-19
2018-02-21
2018-02-26
2018-04-10
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-24
2018-04-25
2018-05-03
2018-04-11
2018-04-12
2018-01-23
2018-01-24
2018-01-25
2018-04-17
2018-05-18
2018-05-21
2018-06-21
2018-06-25
2018-12-18
2018-01-24
2018-05-31
2018-01-16
2018-01-18
2018-01-19
2018-01-22
2018-01-24
2018-01-25
2018-02-05
2018-02-07
2018-02-08
2018-02-09
2018-03-07
2018-03-12
2018-03-13
2018-03-14
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-03
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-30
2018-05-09
2018-05-11
2018-05-25
2018-06-14
2018-06-15
2018-06-20
2018-07-19
2018-07-20
2018-08-03
2018-08-06
2018-08-07
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-14
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-28
2018-10-05
2018-10-15
2018-11-01
2018-01-18
2018-04-16
2018-11-01
2018-11-27
2018-03-21
2018-01-22
2018-03-15
2018-04-17
2018-04-27
2018-01-18
2018-04-27
2018-04-30
2018-05-15
2018-06-05
2018-06-11
2018-06-12
2018-06-14
2018-01-30
2018-01-31
2018-02-01
2018-05-16
2018-05-17
2018-06-11
2018-03-30
2018-04-10
2018-04-11
2018-04-16
2018-06-19
2018-06-21
2018-10-05
2018-11-19
2018-11-20
2018-01-18
2018-02-02
2018-03-13
2018-03-16
2018-03-19
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-10
2018-05-09
2018-05-18
2018-10-19
2018-11-06
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-05-24
2018-08-07
2018-09-14
2018-09-17
2018-09-18
2018-06-14
2018-09-03
2018-07-16
2018-04-11
2018-04-20
2018-04-20
2018-05-24
2018-05-29
2018-04-04
2018-04-19
2018-04-27
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-23
2018-05-24
2018-05-25
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-03
2018-07-06
2018-07-09
2018-07-11
2018-07-24
2018-07-25
2018-07-26
2018-08-10
2018-08-13
2018-08-14
2018-08-16
2018-08-17
2018-08-23
2018-08-27
2018-09-06
2018-09-10
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-10-30
2018-11-23
2018-11-26
2018-12-07
2018-12-13
2018-12-21
2018-03-15
2018-06-28
2018-05-25
2018-06-01
2018-04-13
2018-04-16
2018-07-20
2018-04-16
2018-04-17
2018-05-14
2018-05-17
2018-05-18
2018-05-29
2018-08-09
2018-01-15
2018-01-17
2018-01-19
2018-02-01
2018-02-02
2018-03-12
2018-03-13
2018-04-18
2018-11-20
2018-07-18
2018-07-19
2018-01-23
2018-01-29
2018-01-31
2018-02-01
2018-02-21
2018-02-22
2018-02-23
2018-02-26
2018-02-27
2018-02-28
2018-03-02
2018-03-05
2018-03-06
2018-03-12
2018-03-13
2018-03-14
2018-03-29
2018-04-16
2018-04-26
2018-07-30
2018-03-21
2018-04-26
2018-05-18
2018-01-17
2018-01-18
2018-02-05
2018-02-06
2018-02-06
2018-02-07
2018-02-09
2018-09-28
2018-05-30
2018-06-28
2018-05-03
2018-04-16
2018-04-17
2018-04-18
2018-04-27
2018-05-02
2018-07-03
2018-07-04
2018-03-21
2018-03-05
2018-03-07
2018-03-08
2018-03-09
2018-03-12
2018-03-19
2018-03-28
2018-03-29
2018-04-06
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-06-01
2018-06-12
2018-09-06
2018-12-24
2018-03-08
2018-04-18
2018-04-19
2018-11-08
2018-04-03
2018-04-10
2018-04-11
2018-05-21
2018-05-03
2018-02-20
2018-04-09
2018-04-11
2018-01-17
2018-02-20
2018-02-21
2018-04-06
2018-02-26
2018-03-14
2018-06-25
2018-04-20
2018-04-27
2018-04-30
2018-05-23
2018-05-24
2018-06-12
2018-03-08
2018-03-09
2018-03-28
2018-03-29
2018-04-13
2018-04-17
2018-04-18
2018-04-19
2018-09-06
2018-12-19
2018-01-25
2018-03-30
2018-10-10
2018-01-17
2018-04-02
2018-04-03
2018-03-23
2018-03-26
2018-03-28
2018-04-04
2018-04-06
2018-04-09
2018-04-10
2018-05-09
2018-05-10
2018-05-25
2018-05-29
2018-05-30
2018-05-31
2018-06-04
2018-06-05
2018-06-12
2018-08-09
2018-08-14
2018-10-12
2018-02-05
2018-02-14
2018-01-18
2018-01-23
2018-01-24
2018-06-04
2018-04-24
2018-04-25
2018-02-20
2018-02-21
2018-02-22
2018-03-06
2018-03-29
2018-03-30
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-12-18
2018-03-09
2018-03-23
2018-04-19
2018-04-20
2018-04-23
2018-04-10
2018-01-18
2018-03-22
2018-02-09
2018-01-17
2018-05-02
2018-10-24
2018-10-26
2018-06-19
2018-06-20
2018-01-31
2018-02-22
2018-05-29
2018-05-30
2018-01-18
2018-05-16
2018-05-17
2018-05-25
2018-04-10
2018-05-25
2018-05-28
2018-06-01
2018-06-04
2018-06-05
2018-07-31
2018-08-01
2018-08-03
2018-08-14
2018-08-16
2018-09-04
2018-09-05
2018-12-18
2018-04-19
2018-01-15
2018-03-27
2018-04-10
2018-04-13
2018-02-02
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-20
2018-04-09
2018-05-25
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-07-05
2018-07-31
2018-08-01
2018-08-13
2018-08-14
2018-08-16
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-24
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-03
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-19
2018-09-21
2018-09-28
2018-10-01
2018-10-02
2018-10-08
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-17
2018-10-18
2018-10-19
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-30
2018-10-31
2018-11-02
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-01-18
2018-01-24
2018-01-25
2018-03-15
2018-03-23
2018-03-27
2018-09-20
2018-03-16
2018-09-19
2018-02-01
2018-02-02
2018-02-05
2018-02-07
2018-02-13
2018-04-30
2018-01-30
2018-02-01
2018-02-02
2018-08-03
2018-08-08
2018-02-19
2018-09-19
2018-01-16
2018-10-23
2018-11-01
2018-04-27
2018-04-30
2018-05-03
2018-05-08
2018-05-10
2018-07-27
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-29
2018-01-30
2018-02-01
2018-02-07
2018-02-21
2018-04-24
2018-04-25
2018-04-27
2018-07-17
2018-07-18
2018-07-20
2018-07-25
2018-08-22
2018-05-28
2018-03-08
2018-03-28
2018-06-08
2018-01-26
2018-01-29
2018-01-31
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-13
2018-02-28
2018-03-23
2018-04-04
2018-04-09
2018-04-10
2018-04-12
2018-05-23
2018-05-24
2018-05-25
2018-05-29
2018-05-30
2018-05-31
2018-07-05
2018-09-20
2018-12-26
2018-12-27
2018-09-05
2018-03-08
2018-04-18
2018-05-17
2018-05-18
2018-05-23
2018-05-24
2018-05-28
2018-05-31
2018-06-19
2018-06-20
2018-06-22
2018-07-03
2018-02-22
2018-04-20
2018-04-23
2018-05-03
2018-06-12
2018-06-14
2018-06-15
2018-07-30
2018-07-31
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-29
2018-01-30
2018-02-08
2018-04-05
2018-04-09
2018-05-31
2018-11-16
2018-11-19
2018-05-17
2018-05-21
2018-06-01
2018-06-18
2018-06-19
2018-06-20
2018-09-21
2018-10-04
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-17
2018-12-18
2018-12-24
2018-12-26
2018-12-27
2018-12-28
2018-06-20
2018-04-20
2018-04-04
2018-11-05
2018-11-06
2018-03-22
2018-03-23
2018-04-10
2018-05-16
2018-05-17
2018-08-31
2018-05-04
2018-02-09
2018-01-16
2018-01-17
2018-01-19
2018-01-26
2018-02-01
2018-02-02
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-20
2018-02-26
2018-03-08
2018-03-12
2018-03-14
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-26
2018-03-27
2018-03-28
2018-03-30
2018-04-02
2018-04-05
2018-04-06
2018-04-12
2018-04-18
2018-09-20
2018-01-15
2018-01-17
2018-05-08
2018-09-13
2018-04-25
2018-04-26
2018-06-07
2018-09-10
2018-09-11
2018-09-18
2018-09-19
2018-09-27
2018-05-17
2018-05-23
2018-05-29
2018-05-30
2018-08-10
2018-09-04
2018-09-19
2018-01-31
2018-06-22
2018-06-25
2018-06-28
2018-08-20
2018-01-26
2018-08-08
2018-04-05
2018-04-06
2018-04-23
2018-04-30
2018-05-02
2018-05-14
2018-05-15
2018-05-16
2018-05-28
2018-09-19
2018-05-31
2018-01-19
2018-05-28
2018-08-24
2018-09-13
2018-01-24
2018-02-01
2018-02-06
2018-03-22
2018-04-25
2018-06-04
2018-01-29
2018-02-26
2018-05-02
2018-05-31
2018-07-02
2018-10-01
2018-06-18
2018-05-09
2018-05-11
2018-11-05
2018-11-07
2018-12-03
2018-12-04
2018-12-05
2018-12-10
2018-12-12
2018-12-14
2018-02-05
2018-02-06
2018-02-07
2018-02-09

2018-02-20
2018-02-21
2018-03-22
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-03-09
2018-03-12
2018-03-14
2018-03-15
2018-03-16
2018-03-19
2018-04-02
2018-05-23
2018-06-04
2018-06-07
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-29
2018-07-06
2018-07-12
2018-07-13
2018-07-25
2018-07-30
2018-08-10
2018-09-03
2018-09-11
2018-09-12
2018-09-13
2018-09-18
2018-10-05
2018-10-12
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-11-01
2018-11-02
2018-11-08
2018-11-09
2018-11-13
2018-11-20
2018-11-21
2018-12-03
2018-12-13
2018-12-21
2018-01-26
2018-02-08
2018-03-12
2018-03-13
2018-05-15
2018-05-21
2018-05-31
2018-06-01
2018-05-31
2018-07-26
2018-09-14
2018-12-13
2018-01-23
2018-06-12
2018-06-15
2018-01-25
2018-01-30
2018-02-01
2018-02-06
2018-02-08
2018-02-09
2018-02-28
2018-03-02
2018-03-08
2018-03-09
2018-03-14
2018-03-19
2018-03-23
2018-03-26
2018-03-27
2018-04-10
2018-04-18
2018-04-19
2018-04-30
2018-05-02
2018-05-31
2018-06-14
2018-06-19
2018-07-24
2018-08-30
2018-09-05
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-19
2018-09-21
2018-09-27
2018-09-28
2018-10-04
2018-10-05
2018-10-11
2018-10-30
2018-11-14
2018-11-26
2018-11-28
2018-11-29
2018-11-30
2018-12-03
2018-12-13
2018-10-24
2018-01-29
2018-03-09
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-02
2018-07-03
2018-07-05
2018-07-06
2018-07-09
2018-07-11
2018-07-24
2018-07-25
2018-07-26
2018-08-10
2018-08-13
2018-08-23
2018-08-27
2018-09-10
2018-09-11
2018-09-12
2018-09-19
2018-09-21
2018-10-10
2018-10-11
2018-11-07
2018-04-02
2018-04-30
2018-03-09
2018-03-28
2018-04-19
2018-04-20
2018-04-23
2018-04-30
2018-05-02
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-23
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-11
2018-06-12
2018-06-14
2018-07-24
2018-08-27
2018-09-19
2018-09-21
2018-10-04
2018-10-10
2018-10-11
2018-11-07
2018-03-16
2018-02-06
2018-02-08
2018-02-26
2018-03-08
2018-05-30
2018-05-31
2018-08-08
2018-09-21
2018-10-04
2018-10-31
2018-11-21
2018-12-13
2018-03-27
2018-04-04
2018-04-05
2018-04-06
2018-05-21
2018-05-23
2018-06-26
2018-06-27
2018-06-29
2018-07-17
2018-07-18
2018-10-01
2018-03-09
2018-04-02
2018-04-03
2018-06-28
2018-07-26
2018-07-27
2018-10-04
2018-10-29
2018-10-30
2018-11-15
2018-11-21
2018-11-22
2018-11-27
2018-11-28
2018-12-12
2018-12-13
2018-01-26
2018-02-08
2018-05-10
2018-05-11
2018-11-28
2018-11-29
2018-12-06
2018-12-13
2018-12-21
2018-01-16
2018-04-04
2018-04-20
2018-02-21
2018-01-15
2018-01-16
2018-01-19
2018-01-30
2018-01-31
2018-02-01
2018-02-06
2018-02-20
2018-03-13
2018-04-09
2018-03-09
2018-04-02
2018-07-03
2018-07-09
2018-07-19
2018-07-30
2018-10-04
2018-10-11
2018-11-15
2018-04-09
2018-04-30
2018-05-28
2018-07-26
2018-04-11
2018-01-23
2018-01-24
2018-01-29
2018-02-06
2018-02-07
2018-03-07
2018-03-13
2018-03-27
2018-04-06
2018-04-10
2018-04-20
2018-04-23
2018-05-08
2018-05-31
2018-06-01
2018-06-14
2018-06-21
2018-07-06
2018-07-17
2018-07-27
2018-08-09
2018-08-14
2018-08-21
2018-08-29
2018-09-18
2018-09-19
2018-12-20
2018-03-30
2018-04-03
2018-04-04
2018-04-05
2018-05-02
2018-05-29
2018-06-01
2018-06-07
2018-06-12
2018-06-18
2018-06-19
2018-06-22
2018-06-25
2018-01-17
2018-06-15
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-02-20
2018-04-20
2018-05-02
2018-05-03
2018-06-01
2018-06-04
2018-06-19
2018-07-06
2018-07-09
2018-01-26
2018-04-03
2018-04-04
2018-04-23
2018-04-30
2018-05-02
2018-01-17
2018-03-21
2018-07-11
2018-07-13
2018-07-18
2018-07-19
2018-09-27
2018-09-28
2018-10-01
2018-10-02
2018-05-31
2018-03-28
2018-03-29
2018-03-30
2018-01-24
2018-07-03
2018-11-13
2018-01-24
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-03-09
2018-03-15
2018-03-28
2018-04-10
2018-04-25
2018-05-02
2018-05-03
2018-05-08
2018-05-14
2018-05-23
2018-05-25
2018-05-30
2018-05-31
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-19
2018-06-22
2018-06-27
2018-06-29
2018-07-02
2018-07-12
2018-07-13
2018-07-18
2018-07-19
2018-07-25
2018-07-26
2018-07-27
2018-08-01
2018-08-03
2018-08-06
2018-08-07
2018-08-09
2018-08-21
2018-08-22
2018-08-24
2018-08-27
2018-09-11
2018-09-13
2018-09-18
2018-10-04
2018-10-05
2018-10-11
2018-10-26
2018-10-29
2018-11-07
2018-11-08
2018-11-09
2018-11-28
2018-11-30
2018-12-03
2018-12-21
2018-10-17
2018-10-18
2018-10-19
2018-10-23
2018-10-25
2018-10-26
2018-10-30
2018-10-31
2018-11-02
2018-11-30
2018-12-13
2018-04-26
2018-07-19
2018-01-24
2018-05-16
2018-05-17
2018-02-09
2018-03-08
2018-08-22
2018-09-11
2018-10-10
2018-11-02
2018-12-03
2018-05-11
2018-05-29
2018-05-30
2018-07-25
2018-08-10
2018-02-20
2018-02-21
2018-02-22
2018-05-08
2018-03-22
2018-03-23
2018-03-26
2018-03-30
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-12
2018-04-13
2018-04-16
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-05-02
2018-05-24
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-02-02
2018-04-30
2018-05-02
2018-05-10
2018-05-14
2018-05-16
2018-05-28
2018-05-29
2018-06-08
2018-06-12
2018-06-14
2018-01-16
2018-01-17
2018-01-18
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-02-01
2018-03-27
2018-04-26
2018-05-29
2018-07-20
2018-01-29
2018-10-19
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-13
2018-02-14
2018-02-19
2018-02-20
2018-02-21
2018-02-22
2018-02-23
2018-02-26
2018-02-27
2018-02-28
2018-03-02
2018-03-05
2018-03-06
2018-03-07
2018-03-08
2018-03-09
2018-03-12
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-02
2018-07-03
2018-07-04
2018-07-05
2018-07-06
2018-07-09
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-16
2018-07-17
2018-07-18
2018-07-19
2018-07-20
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-27
2018-07-30
2018-07-31
2018-08-01
2018-08-02
2018-08-03
2018-08-06
2018-08-07
2018-08-08
2018-08-09
2018-08-10
2018-08-13
2018-08-14
2018-08-16
2018-08-17
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-24
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-03
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-21
2018-09-27
2018-09-28
2018-10-01
2018-10-02
2018-10-04
2018-10-05
2018-10-08
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-16
2018-10-17
2018-10-18
2018-10-19
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-16
2018-11-19
2018-11-20
2018-11-21
2018-11-22
2018-11-23
2018-11-26
2018-11-27
2018-11-28
2018-11-29
2018-11-30
2018-12-03
2018-12-04
2018-12-05
2018-12-06
2018-12-07
2018-12-10
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-17
2018-12-18
2018-12-19
2018-12-20
2018-12-21
2018-12-24
2018-12-26
2018-12-27
2018-04-03
2018-05-02
2018-06-19
2018-06-20
2018-01-19
2018-01-22
2018-01-29
2018-01-31
2018-02-01
2018-03-19
2018-03-22
2018-03-23
2018-03-26
2018-03-27
2018-04-10
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-05-03
2018-05-04
2018-05-09
2018-05-17
2018-05-21
2018-05-23
2018-05-31
2018-06-01
2018-06-07
2018-06-15
2018-06-20
2018-06-21
2018-06-22
2018-06-26
2018-07-03
2018-07-04
2018-07-05
2018-07-06
2018-07-09
2018-07-13
2018-07-18
2018-07-20
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-30
2018-07-31
2018-08-02
2018-08-06
2018-08-09
2018-08-10

2018-08-13
2018-08-14
2018-08-20
2018-08-21
2018-08-22
2018-08-24
2018-08-27
2018-08-28
2018-08-29
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-20
2018-09-21
2018-09-27
2018-09-28
2018-10-01
2018-10-02
2018-10-04
2018-10-05
2018-10-08
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-16
2018-10-17
2018-10-18
2018-10-19
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-16
2018-11-19
2018-11-20
2018-11-21
2018-11-22
2018-11-23
2018-11-26
2018-11-27
2018-11-28
2018-11-29
2018-11-30
2018-12-03
2018-12-04
2018-12-05
2018-12-06
2018-12-10
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-17
2018-12-18
2018-12-19
2018-12-20
2018-12-21
2018-12-26
2018-12-27
2018-10-11
2018-03-07
2018-04-23
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-19
2018-12-06
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-05-17
2018-05-18
2018-05-29
2018-06-11
2018-06-12
2018-06-29
2018-04-24
2018-04-26
2018-05-04
2018-09-18
2018-08-31
2018-11-07
2018-11-30
2018-05-14
2018-05-17
2018-05-23
2018-01-19
2018-01-22
2018-01-30
2018-01-31
2018-02-09
2018-02-12
2018-02-20
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-30
2018-07-20
2018-08-23
2018-08-24
2018-08-27
2018-08-28
2018-08-30
2018-09-05
2018-09-06
2018-09-07
2018-09-12
2018-09-19
2018-09-28
2018-10-01
2018-10-02
2018-10-04
2018-10-05
2018-11-05
2018-12-18
2018-01-25
2018-01-29
2018-03-06
2018-03-07
2018-05-08
2018-03-15
2018-03-19
2018-05-10
2018-05-11
2018-02-21
2018-06-27
2018-07-02
2018-05-08
2018-09-06
2018-01-26
2018-02-02
2018-02-08
2018-02-13
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-04
2018-05-23
2018-05-31
2018-06-15
2018-08-08
2018-11-22
2018-12-13
2018-11-30
2018-10-15
2018-10-16
2018-10-19
2018-10-23
2018-10-31
2018-11-02
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-13
2018-11-16
2018-01-26
2018-06-25
2018-01-25
2018-01-26
2018-02-01
2018-02-06
2018-02-07
2018-02-09
2018-02-13
2018-08-02
2018-08-06
2018-08-08
2018-09-28
2018-10-01
2018-04-02
2018-04-17
2018-04-18
2018-04-23
2018-08-31
2018-11-23
2018-07-18
2018-09-19
2018-10-30
2018-03-14
2018-03-15
2018-03-19
2018-03-21
2018-03-22
2018-03-28
2018-03-29
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-18
2018-04-19
2018-04-20
2018-04-25
2018-04-30
2018-05-02
2018-05-09
2018-05-10
2018-05-11
2018-05-16
2018-05-17
2018-02-06
2018-02-19
2018-04-10
2018-02-12
2018-02-13
2018-04-04
2018-04-05
2018-04-11
2018-02-28
2018-03-21
2018-03-22
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-04
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-05-02
2018-05-03
2018-06-01
2018-06-04
2018-06-07
2018-06-08
2018-06-12
2018-06-15
2018-07-04
2018-07-05
2018-07-23
2018-07-24
2018-08-20
2018-08-29
2018-09-04
2018-09-06
2018-09-07
2018-09-12
2018-09-14
2018-05-21
2018-05-23
2018-07-05
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-13
2018-02-14
2018-02-19
2018-02-20
2018-02-21
2018-02-22
2018-02-23
2018-02-26
2018-02-27
2018-02-28
2018-03-02
2018-03-05
2018-03-06
2018-03-07
2018-03-08
2018-03-09
2018-03-12
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-22
2018-03-23
2018-03-26
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-04
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-19
2018-04-20
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-02
2018-07-03
2018-07-04
2018-07-05
2018-07-06
2018-07-09
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-16
2018-07-17
2018-07-18
2018-07-19
2018-07-20
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-27
2018-07-30
2018-07-31
2018-08-01
2018-08-02
2018-08-03
2018-08-06
2018-08-07
2018-08-08
2018-08-09
2018-08-10
2018-08-13
2018-08-14
2018-08-16
2018-08-17
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-03
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-17
2018-09-19
2018-09-20
2018-09-21
2018-09-28
2018-10-01
2018-10-02
2018-10-04
2018-10-05
2018-10-08
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-19
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-05
2018-11-08
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-29
2018-12-04
2018-12-26
2018-12-05
2018-12-14
2018-12-17
2018-12-27
2018-12-28
2018-01-18
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-29
2018-01-30
2018-01-31
2018-02-01
2018-02-02
2018-02-05
2018-02-06
2018-02-07
2018-02-08
2018-02-09
2018-02-12
2018-02-13
2018-02-19
2018-02-26
2018-02-27
2018-03-02
2018-03-05
2018-03-06
2018-03-07
2018-03-08
2018-03-09
2018-03-12
2018-03-13
2018-03-14
2018-03-15
2018-03-16
2018-03-19
2018-03-20
2018-03-21
2018-03-23
2018-03-27
2018-03-28
2018-03-29
2018-03-30
2018-04-02
2018-04-03
2018-04-05
2018-04-06
2018-04-09
2018-04-10
2018-04-11
2018-04-12
2018-04-13
2018-04-16
2018-04-17
2018-04-18
2018-04-23
2018-04-24
2018-04-25
2018-04-26
2018-04-27
2018-04-30
2018-05-02
2018-05-04
2018-05-08
2018-05-09
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-11
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-25
2018-06-27
2018-06-28
2018-06-29
2018-07-06
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-18
2018-07-19
2018-07-26
2018-07-27
2018-07-31
2018-08-17
2018-08-20
2018-09-04
2018-09-05
2018-09-12
2018-09-13
2018-09-14
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-10-01
2018-10-02
2018-10-22
2018-10-30
2018-11-07
2018-11-21
2018-12-20
2018-01-29
2018-01-31
2018-02-05
2018-02-06
2018-03-29
2018-03-30
2018-04-10
2018-04-11
2018-04-12
2018-04-16
2018-04-26
2018-05-02
2018-05-04
2018-09-20
2018-09-21
2018-09-27
2018-09-28
2018-10-02
2018-10-11
2018-12-13
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-11
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-21
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-02
2018-07-03
2018-07-04
2018-07-05
2018-07-06
2018-07-09
2018-07-10
2018-07-11
2018-07-12
2018-07-13
2018-07-16
2018-07-17
2018-07-18
2018-07-19
2018-07-20
2018-07-23
2018-07-24
2018-07-25
2018-07-26
2018-07-27
2018-07-30
2018-07-31
2018-08-01
2018-08-02
2018-08-03
2018-08-06
2018-08-07
2018-08-08
2018-08-09
2018-08-10
2018-08-13
2018-08-14
2018-08-16
2018-08-17
2018-08-20
2018-08-21
2018-08-22
2018-08-23
2018-08-24
2018-08-27
2018-08-28
2018-08-29
2018-08-30
2018-08-31
2018-09-03
2018-09-04
2018-09-05
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-12
2018-09-13
2018-09-14
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-21
2018-09-27
2018-09-28
2018-10-01
2018-10-02
2018-10-04
2018-10-05
2018-10-08
2018-10-10
2018-10-11
2018-10-12
2018-10-15
2018-10-16
2018-10-17
2018-10-18
2018-10-19
2018-10-22
2018-10-23
2018-10-24
2018-10-25
2018-10-26
2018-10-29
2018-10-30
2018-10-31
2018-11-01
2018-11-02
2018-11-05
2018-11-06
2018-11-07
2018-11-08
2018-11-09
2018-11-12
2018-11-13
2018-11-14
2018-11-15
2018-11-16
2018-11-19
2018-11-20
2018-11-21
2018-11-22
2018-11-23
2018-11-26
2018-11-27
2018-11-28
2018-11-29
2018-11-30
2018-12-03
2018-12-04
2018-12-05
2018-12-06
2018-12-07
2018-12-10
2018-12-11
2018-12-12
2018-12-13
2018-12-14
2018-12-17
2018-12-18
2018-12-19
2018-12-20
2018-12-21
2018-12-24
2018-12-26
2018-12-27
2018-12-28
2018-01-16
2018-07-09
2018-08-14
2018-08-21
2018-05-17
2018-05-21
2018-05-23
2018-05-24
2018-04-23
2018-10-25
2018-11-14
2018-11-16
2018-11-19
2018-11-20
2018-04-05
2018-04-27
2018-04-30
2018-05-02
2018-05-03
2018-05-04
2018-05-08
2018-05-09
2018-05-10
2018-05-14
2018-05-15
2018-05-16
2018-05-17
2018-05-18
2018-05-21
2018-05-23
2018-05-24
2018-05-25
2018-05-28
2018-05-29
2018-05-30
2018-05-31
2018-06-01
2018-06-04
2018-06-05
2018-06-07
2018-06-08
2018-06-11
2018-06-12
2018-06-14
2018-06-15
2018-06-18
2018-06-19
2018-06-20
2018-06-22
2018-06-25
2018-06-26
2018-06-27
2018-06-28
2018-06-29
2018-07-11

2018-07-24
2018-07-25
2018-07-26
2018-07-30
2018-07-31
2018-08-10
2018-08-13
2018-08-16
2018-08-17
2018-08-20
2018-08-21
2018-08-27
2018-09-06
2018-09-07
2018-09-10
2018-09-11
2018-09-17
2018-09-18
2018-09-19
2018-09-20
2018-09-21
2018-09-27
2018-10-04
2018-10-10
2018-10-30
2018-11-23
2018-11-26
2018-12-03
2018-01-19
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-31
2018-02-02
2018-02-05
2018-02-06
2018-02-08
2018-02-09
2018-03-19
2018-03-27
2018-03-28
2018-03-29
2018-04-03
2018-04-04
2018-04-17
2018-04-24
2018-04-26
2018-04-27
2018-05-10
2018-05-23
2018-05-24
2018-05-31
2018-06-04
2018-06-14
2018-06-15
2018-06-19
2018-06-27
2018-06-28
2018-07-05
2018-08-08
2018-09-05
2018-09-06
2018-09-07
2018-10-25
2018-11-20
2018-11-22
2018-11-27
2018-11-30
2018-12-12
2018-12-13
2018-12-18
2018-12-19
2018-05-15
2018-05-17
2018-06-07
2018-06-11
2018-06-12

In [60]:
# 아직


from tqdm.notebook import tqdm

dday_alldf = pd.DataFrame()


# need_date가 아닌 cd_dt_dic에서 고르기
for k,(key, val) in tqdm(enumerate(cd_dt_dic.items())):
#     key인 동안에
    for i in val:
        if np.where(x[x['Code']==key]['Date'].values == i)[0][0] >= 9 :
#             pass
    #         i #
    #         "x[x['Code']==key][x['Date']==i]" #
    #         x[x['Code']==key][x['Date']==i] #
            idx = x[x['Code']==key][x['Date']==i].index
    #         'idx.values[0]', idx.values[0] #
            dday_df = pd.DataFrame([x.iloc[:,0:2].loc[idx.values[0]]])
            dday_df.rename(index = {idx.values[0] : i}, inplace = True)
    #         dday_df # 이거의 code와 같은 df인 거 중에서 고르기

            for j in range(9, -1, -1):

    #             idx #

                tmp = x.iloc[idx-j].iloc[:,2:]
                tmp.columns = [f'D-{j}_{ori_col}' for ori_col in x.iloc[:,2:].columns]

                # index가 같아야 한 row에 들어갈 수 있음
    #             idx.values[0]-j #
                tmp = tmp.rename(index = {idx.values[0]-j : i})
    #             tmp #
                dday_df = pd.concat([dday_df, tmp], axis = 1)
#                 break

            dday_df = pd.concat([dday_df, y.iloc[idx]['Next_Change'].rename(index = {idx.values[0]:i})], axis = 1)
            dday_alldf = pd.concat([dday_alldf, dday_df])

    #         dday_alldf #

#             break
#         break


#241되면 멈춤, 12분 안되게 걸림.

0it [00:00, ?it/s]

In [61]:
dday_alldf[dday_alldf['Code']==50120] #아나 킹.... 조건 써놓으니까 50120만 나왔떤거아냐/..?

,Code,Date,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,...,D-0_TSI,D-0_UO,D-0_SR,D-0_WR,D-0_AO,D-0_KAMA,D-0_ROC,D-0_PPO,D-0_PVO,Next_Change
2018-01-15,50120,2018-01-15,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,29.322500,45.3787,63.92280,-36.07720,3645.8800,11858.800000,68.67470,12.324600,38.852000,-0.068182
2018-01-16,50120,2018-01-16,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,28.068900,45.6406,53.25200,-46.74800,3980.7400,11947.600000,47.78580,12.290200,30.627500,-0.188153
2018-01-17,50120,2018-01-17,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,22.313900,41.0354,25.81300,-74.18700,3687.6500,11946.200000,13.10680,10.443300,23.700000,0.047210
2018-01-18,50120,2018-01-18,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,18.879400,41.3833,28.87250,-71.12750,2987.6500,11947.900000,3.38983,9.223990,17.417200,0.012295
2018-01-19,50120,2018-01-19,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,16.538300,33.5502,25.00000,-75.00000,2637.3500,11949.900000,5.10638,8.260690,12.697200,0.137652
2018-01-22,50120,2018-01-22,12800,12950,11300,11700,7846263,91801277100,-0.089494,12220.0,...,16.586600,38.8732,39.13040,-60.86960,2330.7400,11975.800000,11.50790,8.478310,18.701000,0.021352
2018-01-23,50120,2018-01-23,11650,15200,11500,15200,39646571,602627879200,0.299145,12910.0,...,16.931000,38.1931,39.86930,-60.13070,2132.2100,12047.300000,17.62300,8.714070,14.064900,-0.055749
2018-01-24,50120,2018-01-24,13900,18950,11650,12950,111178326,1439759321700,-0.148026,12980.0,...,16.058200,31.2816,29.41180,-70.58820,2312.3500,12080.000000,5.44747,8.294500,7.120210,0.036900
2018-01-25,50120,2018-01-25,15300,15400,12650,13700,57595886,789063638200,0.057915,13280.0,...,15.888200,31.5119,35.94770,-64.05230,2563.8200,12113.000000,20.08550,8.167750,6.807290,0.298932
2018-01-26,50120,2018-01-26,13700,16100,13400,15400,58256770,897154258000,0.124088,13790.0,...,19.843300,48.4298,90.84970,-9.15033,3031.1800,12544.800000,20.06580,10.401400,26.161100,-0.013699
2018-01-29,50120,2018-01-29,14700,15500,14000,14350,19305022,277027065700,-0.068182,14320.0,...,22.426500,43.3164,65.98980,-34.01020,3806.6200,12747.600000,38.99610,11.738500,33.051500,-0.069444
2018-01-30,50120,2018-01-30,13050,13300,11650,11650,19903337,231873876050,-0.188153,13610.0,...,22.688800,40.1735,52.82050,-47.17950,4132.2100,12878.800000,22.26280,11.891600,25.987800,-0.002985
2018-01-31,50120,2018-01-31,12200,13150,11600,12200,18229011,222393934200,0.047210,13460.0,...,22.823000,37.5675,52.30770,-47.69230,4517.3500,13420.200000,8.44156,11.814600,21.158900,-0.011976
2018-02-01,50120,2018-02-01,12200,13750,12100,12350,20744693,256196958550,0.012295,13190.0,...,22.659300,38.9744,50.25640,-49.74360,4657.9400,13776.200000,14.98260,11.491400,14.300400,-0.060606
2018-02-02,50120,2018-02-02,12500,15450,12450,14050,63098632,886535779600,0.137652,12920.0,...,21.180000,38.7672,40.00000,-60.00000,4334.1200,13883.500000,33.04720,10.579600,6.990610,-0.064516
2018-02-05,50120,2018-02-05,14350,15300,13900,14350,23245868,333578205800,0.021352,12920.0,...,18.669000,38.2469,29.74360,-70.25640,3243.9700,13888.900000,18.85250,9.226710,-0.053288,0.017241
2018-02-06,50120,2018-02-06,14450,14800,13550,13550,10948361,148350291550,-0.055749,13300.0,...,16.885000,35.5135,32.30770,-67.69230,2319.4100,13895.800000,19.43320,8.195060,-5.180440,-0.084746
2018-02-07,50120,2018-02-07,13600,15400,13600,14050,32155164,451780054200,0.036900,13670.0,...,13.818600,34.5633,15.13510,-84.86490,1592.3500,13894.000000,-3.91459,6.632440,-8.227760,0.018519
2018-02-12,50120,2018-02-12,18200,18550,16550,16750,28291666,473885405500,-0.069444,16120.0,...,7.294420,33.1250,7.55814,-92.44190,186.1760,13605.000000,-4.62633,3.257720,-23.403200,0.026119
2018-02-19,50120,2018-02-19,16300,16850,15000,15500,12302624,190690672000,-0.060606,16690.0,...,4.944520,27.3542,18.60470,-81.39530,-226.3240,13687.975172,-14.32840,2.037190,-33.637000,-0.013937
2018-02-21,50120,2018-02-21,13700,14750,12750,14750,13510914,199285981500,0.017241,15590.0,...,5.186560,32.9620,35.65220,-64.34780,-86.3235,13724.800000,-10.30300,2.063260,-33.502300,0.000000
2018-02-26,50120,2018-02-26,13200,14500,13150,13250,6964523,92279929750,-0.036364,13950.0,...,4.253450,35.3776,46.66670,-53.33330,54.7059,13739.600000,-4.06780,1.562320,-38.818300,-0.021201
2018-04-10,50120,2018-04-10,12700,12750,11600,11750,2031262,23867328500,-0.060000,11930.0,...,-17.761100,39.8322,51.56250,-48.43750,-1430.1500,12119.300000,7.92952,-4.147200,9.597470,-0.036735
2018-04-17,50120,2018-04-17,11400,11500,10650,10700,1848128,19774969600,-0.048889,11290.0,...,-1.480640,46.0528,83.69570,-16.30430,135.7350,12493.600000,22.97870,-0.213207,42.797100,-0.100346
2018-04-18,50120,2018-04-18,10850,11400,10750,10900,1716184,18706405600,0.018692,11200.0,...,0.808038,39.1073,52.17390,-47.82610,474.2650,12531.700000,14.03510,0.344193,41.793600,-0.011539
2018-04-19,50120,2018-04-19,10900,10950,10600,10800,1092906,11803384800,-0.009174,11010.0,...,2.097040,34.3881,48.91300,-51.08700,735.2940,12550.600000,14.22220,0.676097,34.705700,0.042802
2018-04-20,50120,2018-04-20,10750,11350,10750,11150,1071724,11949722600,0.032407,10960.0,...,4.284240,36.9507,60.86960,-39.13040,995.8820,12621.100000,25.23360,1.277660,31.074800,-0.022388
2018-04-24,50120,2018-04-24,12300,12800,11800,11800,7196044,84913319200,-0.036735,11380.0,...,8.417420,44.4105,80.43480,-19.56520,1186.1800,12742.100000,32.40740,2.471100,18.323100,-0.027972
2018-04-25,50120,2018-04-25,11900,12450,11600,12050,6600737,79538880850,0.021186,11610.0,...,9.887830,42.3158,71.73910,-28.26090,1201.6200,12811.700000,24.66370,2.910690,15.216300,-0.014389
2018-05-03,50120,2018-05-03,13250,13800,12750,12850,8989837,115519405450,-0.011539,12870.0,...,9.226940,38.6561,42.42420,-57.57580,1132.5000,12920.300000,9.46502,2.526090,-6.306060,0.003759

In [78]:
# 아직


from tqdm.notebook import tqdm

dday_alldf = pd.DataFrame()


# need_date가 아닌 cd_dt_dic에서 고르기
for k,(key, val) in tqdm(enumerate(cd_dt_dic.items())):
#     k
#     if 3 <= k <=10 :
    #     key인 동안에
        for i in val:
            if np.where(x[x['Code']==key]['Date'].values == i)[0][0] >= 9 :
        #         i #
        #         "x[x['Code']==key][x['Date']==i]" #
        #         x[x['Code']==key][x['Date']==i] #
                idx = x[x['Code']==key][x['Date']==i].index
#                 'idx.values[0]', idx.values[0] #
                dday_df = pd.DataFrame([x.iloc[:,0:2].loc[idx.values[0]]])
                dday_df.rename(index = {idx.values[0] : i}, inplace = True)
                dday_df # 이거의 code와 같은 df인 거 중에서 고르기

                for j in range(9, -1, -1):

#                     idx #

                    tmp = x.iloc[idx-j].iloc[:,2:]
                    tmp.columns = [f'D-{j}_{ori_col}' for ori_col in x.iloc[:,2:].columns]

                    # index가 같아야 한 row에 들어갈 수 있음
        #             idx.values[0]-j #
                    tmp = tmp.rename(index = {idx.values[0]-j : i})
        #             tmp #
                    dday_df = pd.concat([dday_df, tmp], axis = 1)
        #             break

                dday_df = pd.concat([dday_df, y.iloc[idx]['Next_Change'].rename(index = {idx.values[0]:i})], axis = 1)
                dday_alldf = pd.concat([dday_alldf, dday_df])

        #         dday_alldf #

        #         break
    #         break
#     elif k>10:
#         break
dday_alldf

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 46)

# 답!!!!!!!!!!!! (not using readlines)

In [82]:
# 답!!!!!!!!!!!!!!

from tqdm.notebook import tqdm

dday_alldf = pd.DataFrame()


# need_date가 아닌 cd_dt_dic에서 고르기
for k,(key, val) in tqdm(enumerate(cd_dt_dic.items())):
#     key인 동안에
    for i in val:
        if np.where(x[x['Code']==key]['Date'].values == i)[0][0] >= 9 :
    #         i #
    #         "x[x['Code']==key][x['Date']==i]" #
    #         x[x['Code']==key][x['Date']==i] #
            idx = x[x['Code']==key][x['Date']==i].index
#             'idx.values[0]', idx.values[0] #
            dday_df = pd.DataFrame([x.iloc[:,0:2].loc[idx.values[0]]])
            dday_df.rename(index = {idx.values[0] : i}, inplace = True)
#             dday_df # 이거의 code와 같은 df인 거 중에서 고르기

            for j in range(9, -1, -1):

#                     idx #

                tmp = x.iloc[idx-j].iloc[:,2:]
                tmp.columns = [f'D-{j}_{ori_col}' for ori_col in x.iloc[:,2:].columns]

                # index가 같아야 한 row에 들어갈 수 있음
    #             idx.values[0]-j #
                tmp = tmp.rename(index = {idx.values[0]-j : i})
    #             tmp #
                dday_df = pd.concat([dday_df, tmp], axis = 1)
    #             break

            dday_df = pd.concat([dday_df, y.iloc[idx]['Next_Change'].rename(index = {idx.values[0]:i})], axis = 1)
            dday_alldf = pd.concat([dday_alldf, dday_df])

    #         dday_alldf #

#         break
#     break

0it [00:00, ?it/s]

In [83]:
dday_alldf

,Code,Date,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,...,D-0_TSI,D-0_UO,D-0_SR,D-0_WR,D-0_AO,D-0_KAMA,D-0_ROC,D-0_PPO,D-0_PVO,Next_Change
2018-01-15,50120,2018-01-15,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,29.3225,45.3787,63.9228,-36.07720,3645.880000,11858.8,68.67470,12.32460,38.8520,-0.068182
2018-01-16,50120,2018-01-16,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,28.0689,45.6406,53.2520,-46.74800,3980.740000,11947.6,47.78580,12.29020,30.6275,-0.188153
2018-01-17,50120,2018-01-17,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,22.3139,41.0354,25.8130,-74.18700,3687.650000,11946.2,13.10680,10.44330,23.7000,0.047210
2018-01-18,50120,2018-01-18,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,18.8794,41.3833,28.8725,-71.12750,2987.650000,11947.9,3.38983,9.22399,17.4172,0.012295
2018-01-19,50120,2018-01-19,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,16.5383,33.5502,25.0000,-75.00000,2637.350000,11949.9,5.10638,8.26069,12.6972,0.137652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-05-15,11760,2018-05-15,21400,24100,20800,22400,1488904,33351449600,0.095354,20830.0,...,56.6722,68.0251,84.6369,-15.36310,6866.910000,27722.5,74.93730,13.01120,68.4751,-0.097421
2018-05-17,11760,2018-05-17,23500,23850,21950,22350,489326,10936436100,-0.064854,22040.0,...,54.5403,64.0099,85.1942,-14.80580,10338.970588,29517.6,83.12960,15.48880,67.1178,0.028037
2018-06-07,11760,2018-06-07,41650,41900,37000,38800,1305256,50643932800,-0.058252,39190.0,...,29.5457,49.8274,70.6329,-29.36710,10088.100000,36598.8,11.81820,13.02900,17.8270,-0.001161
2018-06-11,11760,2018-06-11,40500,41300,40050,41300,712521,29427117300,0.298742,38620.0,...,31.8637,53.8917,95.8333,-4.16667,10979.700000,39093.7,20.87380,13.90680,19.4140,-0.038153
2018-06-12,11760,2018-06-12,42650,44650,39500,40700,2115221,86089494700,-0.014528,38760.0,...,32.4200,52.7160,75.5020,-24.49800,12323.800000,39605.8,23.45360,14.10110,25.2156,-0.155532

In [86]:
# dday_alldf.to_csv('first_stock_2018_10days.csv', index = False)

In [89]:
pd.read_csv('first_stock_2018_10days.csv')

,Code,Date,D-9_Open,D-9_High,D-9_Low,D-9_Close,D-9_Volume,D-9_Trading_Value,D-9_Change,D-9_MA5,...,D-0_TSI,D-0_UO,D-0_SR,D-0_WR,D-0_AO,D-0_KAMA,D-0_ROC,D-0_PPO,D-0_PVO,Next_Change
0,50120,2018-01-15,10250,12050,10150,11800,26086769,307823874200,0.145631,10108.0,...,29.3225,45.3787,63.9228,-36.07720,3645.880000,11858.8,68.67470,12.32460,38.8520,-0.068182
1,50120,2018-01-16,11950,12450,10900,11750,20460474,240410569500,-0.004237,10538.0,...,28.0689,45.6406,53.2520,-46.74800,3980.740000,11947.6,47.78580,12.29020,30.6275,-0.188153
2,50120,2018-01-17,11850,14150,11600,12600,60663854,764364560400,0.072340,11232.0,...,22.3139,41.0354,25.8130,-74.18700,3687.650000,11946.2,13.10680,10.44330,23.7000,0.047210
3,50120,2018-01-18,12800,13200,12000,12200,13935258,170010147600,-0.031746,11730.0,...,18.8794,41.3833,28.8725,-71.12750,2987.650000,11947.9,3.38983,9.22399,17.4172,0.012295
4,50120,2018-01-19,12450,13400,12350,12850,16471707,211661434950,0.053279,12240.0,...,16.5383,33.5502,25.0000,-75.00000,2637.350000,11949.9,5.10638,8.26069,12.6972,0.137652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2532,11760,2018-05-15,21400,24100,20800,22400,1488904,33351449600,0.095354,20830.0,...,56.6722,68.0251,84.6369,-15.36310,6866.910000,27722.5,74.93730,13.01120,68.4751,-0.097421
2533,11760,2018-05-17,23500,23850,21950,22350,489326,10936436100,-0.064854,22040.0,...,54.5403,64.0099,85.1942,-14.80580,10338.970588,29517.6,83.12960,15.48880,67.1178,0.028037
2534,11760,2018-06-07,41650,41900,37000,38800,1305256,50643932800,-0.058252,39190.0,...,29.5457,49.8274,70.6329,-29.36710,10088.100000,36598.8,11.81820,13.02900,17.8270,-0.001161
2535,11760,2018-06-11,40500,41300,40050,41300,712521,29427117300,0.298742,38620.0,...,31.8637,53.8917,95.8333,-4.16667,10979.700000,39093.7,20.87380,13.90680,19.4140,-0.038153
2536,11760,2018-06-12,42650,44650,39500,40700,2115221,86089494700,-0.014528,38760.0,...,32.4200,52.7160,75.5020,-24.49800,12323.800000,39605.8,23.45360,14.10110,25.2156,-0.155532

# with open, readlines ver

In [ ]:
f = open('stock_2018.csv')
lines = f.readlines()
for line in tqdm(lines):
    line = line.strip()
    line
    break