<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#library" data-toc-modified-id="library-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>library</a></span></li><li><span><a href="#data-('조건df.csv')" data-toc-modified-id="data-('조건df.csv')-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>data ('조건df.csv')</a></span></li><li><span><a href="#mk_cd-함수" data-toc-modified-id="mk_cd-함수-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>mk_cd 함수</a></span></li><li><span><a href="#xxxx-data-('보조지표추가_cd_nuniq=2348.ftr')" data-toc-modified-id="xxxx-data-('보조지표추가_cd_nuniq=2348.ftr')-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>xxxx data ('보조지표추가_cd_nuniq=2348.ftr')</a></span></li><li><span><a href="#mk_cd-적용" data-toc-modified-id="mk_cd-적용-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>mk_cd 적용</a></span></li><li><span><a href="#oooo!!!!-data-('조건만족cd_dt-(by-ffin).txt')" data-toc-modified-id="oooo!!!!-data-('조건만족cd_dt-(by-ffin).txt')-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>oooo!!!! data ('조건만족cd_dt (by ffin).txt')</a></span></li><li><span><a href="#oooo!!!!-data('nc추가.ftr')" data-toc-modified-id="oooo!!!!-data('nc추가.ftr')-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>oooo!!!! data('nc추가.ftr')</a></span><ul class="toc-item"><li><span><a href="#nc_df에-mk_cd-함수-적용" data-toc-modified-id="nc_df에-mk_cd-함수-적용-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>nc_df에 mk_cd 함수 적용</a></span></li></ul></li><li><span><a href="#조건만족-cddt에-해당하는-cd-dt와-일치하는-data에-대해-그거-포함-앞-10개-날짜의-data-뽑기" data-toc-modified-id="조건만족-cddt에-해당하는-cd-dt와-일치하는-data에-대해-그거-포함-앞-10개-날짜의-data-뽑기-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>조건만족 cddt에 해당하는 cd dt와 일치하는 data에 대해 그거 포함 앞 10개 날짜의 data 뽑기</a></span></li><li><span><a href="#10개-날짜씩-옆으로-잇기" data-toc-modified-id="10개-날짜씩-옆으로-잇기-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>10개 날짜씩 옆으로 잇기</a></span></li></ul></div>

# library

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# data ('조건df.csv')

In [2]:
조건df = pd.read_csv('조건df.csv')
조건df['code'].nunique()

2377

# mk_cd 함수

In [3]:
def mk_cd(x):
    if type(x) == str:
        if x.isalpha():
            return x
        else:
            if len(x) == 6:
                return x
            else:
                return "0"*(6-len(x))+x
    elif type(x) == int:
        x = str(x)
        return "0"*(6-len(x))+x

In [4]:
조건df['code'] = list(map(mk_cd, 조건df['code']))

In [5]:
조건df['code'].nunique()

2371

# xxxx data ('보조지표추가_cd_nuniq=2348.ftr')

In [42]:
보조지표df = pd.read_feather('보조지표추가_cd_nuniq=2348.ftr', columns = None, use_threads = True)

In [43]:
보조지표df

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
0,19960701,000010,36496,37676,36496,37588,14499,542221500,1.18,NaN,...,0.000000,0.000000,0.000000,92.542373,-7.457627,0.000000,37588.000000,0.000000,0.000000,0.000000
1,19960702,000010,37588,38462,37151,37938,30476,1153293600,0.93,NaN,...,0.000000,100.000000,31.593737,73.346897,-26.653103,0.000000,37743.555556,0.000000,0.074228,8.127021
2,19960703,000010,38025,38025,37151,37719,18375,694638000,-0.58,NaN,...,0.000000,98.619124,40.267459,62.207528,-37.792472,0.000000,37732.880541,0.000000,0.085075,8.142756
3,19960704,000010,37719,37938,37151,37370,22539,849041000,-0.93,NaN,...,0.000000,95.325955,37.909441,44.455748,-55.544252,0.000000,37580.577800,0.000000,0.018624,9.925574
4,19960705,000010,37151,38025,37151,38025,15830,595899300,1.75,37728.0,...,0.000000,92.826559,48.706725,77.772126,-22.227874,0.000000,37767.295870,0.000000,0.105182,8.153143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6854873,20220325,950210,19400,21050,17250,17750,2884592,55832885600,-3.01,15730.0,...,0.886111,2.571420,54.711042,59.756098,-40.243902,659.264706,15704.276412,31.481481,0.730444,66.393691
6854874,20220328,950210,17650,18150,17450,18050,432272,7718272800,1.69,16510.0,...,0.918642,8.403671,55.985908,63.414634,-36.585366,1297.205882,16198.537285,33.210332,2.130543,56.425429
6854875,20220329,950210,17900,21400,17500,19800,5156123,103299163150,9.70,17600.0,...,1.000000,15.800461,55.988631,81.286550,-18.713450,2238.676471,17076.125215,40.425532,4.034409,75.501358
6854876,20220330,950210,20250,22500,19450,19800,2072532,43571439650,0.00,18740.0,...,1.000000,21.143478,50.227010,72.020725,-27.979275,3473.676471,17737.179572,48.872180,5.409680,68.857624
6854877,20220331,950210,19500,20500,19150,20300,511003,10140785700,2.53,19140.0,...,1.000000,25.885194,52.108588,77.202073,-22.797927,4133.382353,18361.675910,49.264706,6.603329,56.740704

In [9]:
보조지표df['code'].nunique()

2348

# mk_cd 적용

In [15]:
보조지표df['code'] = pd.DataFrame(map(mk_cd,보조지표df['code']))

In [16]:
보조지표df['code'].nunique()

2348

In [29]:
보조지표df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6854878 entries, 0 to 6854877
Data columns (total 58 columns):
 #   Column         Dtype
---  ------         -----
 0   date           int64
 1   code           object
 2   open           int64
 3   high           int64
 4   low            int64
 5   close          int64
 6   volume         int64
 7   tradingvalue   int64
 8   change         float64
 9   ma_5           float64
 10  ma_20          float64
 11  ma_60          float64
 12  ma_120         float64
 13  MFI            float64
 14  ADI            float64
 15  OBV            int64
 16  CMF            float64
 17  FI             float64
 18  EOM, EMV       float64
 19  VPT            float64
 20  NVI            float64
 21  VMAP           float64
 22  ATR            float64
 23  BHB            float64
 24  BLB            float64
 25  KCH            float64
 26  KCL            float64
 27  KCM            float64
 28  DCH            float64
 29  DCL            float64
 30  DCM            float64
 31  UI             float64
 32  SMA            float64
 33  EMA            float64
 34  WMA            float64
 35  MACD           float64
 36  ADX            float64
 37  -VI            float64
 38  +VI            float64
 39  TRIX           float64
 40  MI             float64
 41  CCI            float64
 42  DPO            float64
 43  KST            float64
 44  Ichimoku       float64
 45  Parabolic SAR  float64
 46  STC            float64
 47  RSI            float64
 48  SRSI           float64
 49  TSI            float64
 50  UO             float64
 51  SR             float64
 52  WR             float64
 53  AO             float64
 54  KAMA           float64
 55  ROC            float64
 56  PPO            float64
 57  PVO            float64
dtypes: float64(49), int64(8), object(1)
memory usage: 3.0+ GB

# oooo!!!! data ('조건만족cd_dt (by ffin).txt')

In [6]:
f = open('조건만족cd_dt (by ffin).txt', 'r', encoding = 'utf-8')
l = f.readlines()

In [41]:
for iter, i in tqdm(enumerate(l)):
    i = i.strip()
    i = i.split('\t') # 문자열로 나옴
    cd = i[0]
    dt = i[1]
    if iter == 0:
        pass
    else:
        dt = int(dt)
#         보조지표df.iloc[np.where((보조지표df['code'] == cd) & (보조지표df['date'] == dt))] # 각 조건 괄호로 묶어줘야 결과 출력됨.
        조건idx = 보조지표df.iloc[np.where((보조지표df['code'] == cd) & (보조지표df['date'] == dt))].index.values[0]
        보조지표df.iloc[조건idx-9:조건idx+1]
f.close()

0it [00:00, ?it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
59,19960910,000010,37807,38113,37676,37850,17585,666446300,0.46,37623.0,...,1.000000,11.301074,58.207669,90.906389,-9.093611,973.867647,36610.826858,8.248012,0.825861,17.541632
60,19960911,000010,37850,38025,37457,37850,19569,738559900,0.00,37736.6,...,1.000000,13.150384,61.194620,90.906389,-9.093611,1016.435294,36703.617782,7.979346,0.962022,12.667179
61,19960912,000010,37588,37850,37239,37807,18725,704567800,-0.12,37754.2,...,0.978614,14.540704,57.077550,89.059561,-10.940439,1048.376471,36797.189212,5.617946,1.047693,8.338236
62,19960913,000010,37763,37763,37195,37282,23287,870083500,-1.39,37693.0,...,0.667843,14.031414,56.837611,71.833709,-28.166291,962.402941,36875.621471,2.400571,0.989763,6.016700
63,19960914,000010,37151,37239,36801,37151,16167,599686900,-0.35,37588.0,...,0.596138,13.195258,51.944891,66.184388,-33.815612,814.035294,36917.737833,2.409240,0.904950,1.995936
64,19960916,000010,37064,37719,37064,37326,22166,830147600,0.47,37483.2,...,0.680551,12.940648,53.541998,72.072678,-27.927322,701.861765,36920.354933,5.823316,0.865741,0.530428
65,19960917,000010,37195,37719,37195,37719,16636,622768400,1.05,37457.0,...,0.860703,13.729078,58.179802,85.296097,-14.703903,639.914706,36949.186036,7.204980,0.909286,-2.422356
66,19960918,000010,37588,37807,37588,37719,22616,853064600,0.00,37439.4,...,0.860703,14.380319,61.261600,85.296097,-14.703903,670.514706,36952.390256,1.172147,0.932735,-2.831470
67,19960919,000010,37807,37807,37151,37282,27309,1020187000,-1.16,37439.4,...,0.000000,13.395265,56.271576,39.389736,-60.610264,672.441176,36960.643488,0.000000,0.846921,-1.586533
68,19960920,000010,37151,37370,35403,36277,42732,1548596200,-2.70,37264.6,...,0.000000,9.148998,48.350147,31.747185,-68.252815,570.800000,36873.652994,-3.823007,0.554780,4.094900

2it [00:00,  7.11it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
65,19960917,000010,37195,37719,37195,37719,16636,622768400,1.05,37457.0,...,0.860703,13.729078,58.179802,85.296097,-14.703903,639.914706,36949.186036,7.204980,0.909286,-2.422356
66,19960918,000010,37588,37807,37588,37719,22616,853064600,0.00,37439.4,...,0.860703,14.380319,61.261600,85.296097,-14.703903,670.514706,36952.390256,1.172147,0.932735,-2.831470
67,19960919,000010,37807,37807,37151,37282,27309,1020187000,-1.16,37439.4,...,0.000000,13.395265,56.271576,39.389736,-60.610264,672.441176,36960.643488,0.000000,0.846921,-1.586533
68,19960920,000010,37151,37370,35403,36277,42732,1548596200,-2.70,37264.6,...,0.000000,9.148998,48.350147,31.747185,-68.252815,570.800000,36873.652994,-3.823007,0.554780,4.094900
69,19960921,000010,36146,37588,35621,37413,24493,889436100,3.13,37282.0,...,0.577202,8.941536,60.968544,73.011260,-26.988740,426.914706,36883.186762,-0.465574,0.563154,2.925305
70,19960923,000010,37588,38244,36889,38025,68792,2588880000,1.64,37343.2,...,0.821257,10.386259,63.134661,92.291447,-7.708553,429.535294,36892.060948,0.926319,0.694182,13.791220
71,19960924,000010,37632,38681,37632,38681,40918,1565992200,1.72,37535.6,...,1.000000,13.105788,69.232814,100.000000,-0.000000,488.555882,36942.743774,2.195509,0.927977,14.395439
72,19960925,000010,38681,40211,38681,39817,47592,1879652900,2.94,38042.6,...,1.000000,17.747679,69.199878,91.805324,-8.194676,824.102941,37261.869877,5.196830,1.338924,16.088133
73,19960930,000010,40211,40298,38899,39336,40746,1606384300,-1.21,38654.4,...,0.817747,19.686386,64.941677,80.347293,-19.652707,1394.532353,37427.600218,4.044225,1.540871,15.617985
74,19961001,000010,40211,40211,37195,37501,835032,33396100000,-4.67,38672.0,...,0.273435,15.743477,54.854891,42.860061,-57.139939,1756.379412,37428.049275,0.587415,1.295706,74.523403

3it [00:00,  4.75it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
69,19960921,000010,36146,37588,35621,37413,24493,889436100,3.13,37282.0,...,0.577202,8.941536,60.968544,73.011260,-26.988740,426.914706,36883.186762,-0.465574,0.563154,2.925305
70,19960923,000010,37588,38244,36889,38025,68792,2588880000,1.64,37343.2,...,0.821257,10.386259,63.134661,92.291447,-7.708553,429.535294,36892.060948,0.926319,0.694182,13.791220
71,19960924,000010,37632,38681,37632,38681,40918,1565992200,1.72,37535.6,...,1.000000,13.105788,69.232814,100.000000,-0.000000,488.555882,36942.743774,2.195509,0.927977,14.395439
72,19960925,000010,38681,40211,38681,39817,47592,1879652900,2.94,38042.6,...,1.000000,17.747679,69.199878,91.805324,-8.194676,824.102941,37261.869877,5.196830,1.338924,16.088133
73,19960930,000010,40211,40298,38899,39336,40746,1606384300,-1.21,38654.4,...,0.817747,19.686386,64.941677,80.347293,-19.652707,1394.532353,37427.600218,4.044225,1.540871,15.617985
74,19961001,000010,40211,40211,37195,37501,835032,33396100000,-4.67,38672.0,...,0.273435,15.743477,54.854891,42.860061,-57.139939,1756.379412,37428.049275,0.587415,1.295706,74.523403
75,19961002,000010,37544,38156,36933,37588,38760,1454308800,0.23,38584.6,...,0.294948,13.087764,55.548750,44.637385,-55.362615,1717.905882,37428.953742,1.176281,1.107145,61.065152
76,19961004,000010,37151,37544,36277,36277,26433,971372600,-3.49,38103.8,...,0.000000,7.847437,47.095991,17.854954,-82.145046,1446.205882,37397.832063,-2.810373,0.669986,48.612846
77,19961005,000010,35840,36277,35840,36277,12186,439212800,0.00,37395.8,...,0.000000,3.992908,45.480535,17.854954,-82.145046,763.558824,37376.552135,-3.823007,0.318417,36.641917
78,19961007,000010,36496,38375,36496,37588,31889,1187210600,3.61,37046.2,...,0.332074,3.767677,45.085356,44.637385,-55.362615,273.105882,37381.743166,-0.347305,0.317907,27.495080

4it [00:00,  4.05it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
114,19961118,000010,31513,32999,31513,32125,10401,338695300,-3.42,31993.4,...,0.684484,-32.649264,40.405083,21.505906,-78.494094,-2994.302941,32483.129997,-4.546130,-3.318101,-32.379078
115,19961119,000010,32125,32518,31513,31906,12202,390575800,-0.68,32028.4,...,0.629689,-31.347183,42.675353,19.981696,-80.018304,-2891.258824,32467.995440,-3.566463,-3.259838,-30.898716
116,19961120,000010,31950,31950,31469,31469,5077,160634200,-1.37,32037.2,...,0.521765,-30.997163,39.732711,9.068220,-90.931780,-2723.061765,32429.424712,-5.637350,-3.285685,-33.670946
117,19961121,000010,31076,31688,30639,30814,15542,484923300,-2.08,31915.0,...,0.371316,-31.687793,40.481815,5.802387,-94.197613,-2624.911765,32381.223704,-6.249239,-3.432579,-29.409709
118,19961122,000010,30814,30814,29939,30027,14977,455705000,-2.55,31268.2,...,0.210548,-33.340976,38.547094,2.368138,-97.631862,-2773.829412,32246.365480,-8.643666,-3.708826,-26.050503
119,19961125,000010,30158,30158,29065,29065,18338,540928700,-3.20,30656.2,...,0.041562,-35.910457,35.772438,0.000000,-100.000000,-3077.126471,31838.077635,-8.904281,-4.132517,-21.184721
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891

5it [00:01,  3.72it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
117,19961121,000010,31076,31688,30639,30814,15542,484923300,-2.08,31915.0,...,0.371316,-31.687793,40.481815,5.802387,-94.197613,-2624.911765,32381.223704,-6.249239,-3.432579,-29.409709
118,19961122,000010,30814,30814,29939,30027,14977,455705000,-2.55,31268.2,...,0.210548,-33.340976,38.547094,2.368138,-97.631862,-2773.829412,32246.365480,-8.643666,-3.708826,-26.050503
119,19961125,000010,30158,30158,29065,29065,18338,540928700,-3.20,30656.2,...,0.041562,-35.910457,35.772438,0.000000,-100.000000,-3077.126471,31838.077635,-8.904281,-4.132517,-21.184721
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344

6it [00:01,  3.55it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
120,19961126,000010,29065,29939,29065,29502,10188,301117900,1.50,30175.4,...,0.239175,-36.674053,27.361288,10.306604,-89.693396,-3363.855882,31676.952866,-7.788960,-4.316403,-21.746408
121,19961127,000010,29502,29939,29284,29502,19875,586642700,0.00,29782.0,...,0.206182,-37.268826,26.977699,10.306604,-89.693396,-3555.279412,31547.980473,-9.397457,-4.417569,-16.477509
122,19961128,000010,29502,29896,28847,29109,18308,537056100,-1.33,29441.0,...,0.123894,-38.237571,25.968130,5.877075,-94.122925,-3679.076471,31373.131748,-8.263213,-4.553466,-13.076662
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344
127,19961204,000010,26443,26661,25831,25831,114947,3010894600,-3.90,27561.8,...,0.000000,-48.285700,30.338011,0.000000,-100.000000,-4190.088235,27629.006809,-19.040306,-6.007740,35.084937
128,19961205,000010,25831,26618,25394,26224,81474,2138908300,1.52,27107.2,...,0.205638,-49.596656,33.475376,11.650758,-88.349242,-4319.752941,27300.289142,-16.667196,-6.285038,38.593890
129,19961206,000010,26443,27098,24913,24913,116347,2995709500,-5.00,26407.8,...,0.041689,-51.905515,28.764844,0.000000,-100.000000,-4633.055882,26716.092917,-19.150386,-6.815319,44.246628

7it [00:01,  3.44it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,SRSI,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO
123,19961129,000010,29546,29546,26880,28497,81158,2340157900,-2.10,29135.0,...,0.003697,-39.769427,35.240071,25.167315,-74.832685,-3852.747059,30427.754030,-9.317422,-4.774196,15.166891
124,19961130,000010,30245,30245,27798,28410,6523,188681700,-0.31,29004.0,...,0.000000,-41.100929,35.155783,23.813230,-76.186770,-3721.997059,29812.972342,-9.594272,-4.923753,7.663850
125,19961202,000010,28410,28628,27973,28191,29629,841648100,-0.77,28741.8,...,0.000000,-42.446946,36.617135,20.404669,-79.595331,-3698.767647,29318.779848,-15.243077,-5.050229,9.734916
126,19961203,000010,28147,28147,26661,26880,45098,1223676500,-4.65,28217.4,...,0.000000,-45.075455,36.539789,3.296207,-96.703793,-3866.444118,28525.498651,-16.326848,-5.452434,15.938344
127,19961204,000010,26443,26661,25831,25831,114947,3010894600,-3.90,27561.8,...,0.000000,-48.285700,30.338011,0.000000,-100.000000,-4190.088235,27629.006809,-19.040306,-6.007740,35.084937
128,19961205,000010,25831,26618,25394,26224,81474,2138908300,1.52,27107.2,...,0.205638,-49.596656,33.475376,11.650758,-88.349242,-4319.752941,27300.289142,-16.667196,-6.285038,38.593890
129,19961206,000010,26443,27098,24913,24913,116347,2995709500,-5.00,26407.8,...,0.041689,-51.905515,28.764844,0.000000,-100.000000,-4633.055882,26716.092917,-19.150386,-6.815319,44.246628
130,19961207,000010,25350,25787,25350,25569,99311,2529770500,2.63,25883.4,...,0.469681,-51.733315,27.473997,9.682657,-90.317343,-4888.926471,26476.317167,-14.846638,-6.986947,44.471683
131,19961209,000010,25831,26530,25350,25350,187004,4829544300,-0.85,25577.4,...,0.518486,-51.803448,25.057531,7.405524,-92.594476,-4914.329412,26233.264213,-12.781696,-7.118298,51.187343
132,19961210,000010,25438,27098,25350,26661,66687,1743489800,5.17,25743.4,...,1.000000,-48.114751,31.681519,32.783196,-67.216804,-4661.611765,26264.483418,-9.629856,-6.768226,44.340891

8it [00:02,  3.30it/s]

KeyboardInterrupt:

# oooo!!!! data('nc추가.ftr')

In [7]:
nc_df = pd.read_feather('nc추가.ftr', columns = None, use_threads = True)
nc_df['code'].nunique()
nc_df

2348

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO,next_change
0,19960724,000010,1.000000,1.010967,0.987836,0.987836,11330,405933000,-1.22,1.004871,...,14.833178,38.017009,12.620424,-87.379576,-744.175000,1.019623,-6.344012,-1.318437,-6.161058,-1.48
1,19960725,000010,1.000000,1.000000,0.985235,0.985235,12568,442868900,-1.48,1.009856,...,10.492089,32.752921,0.000000,-100.000000,-785.980952,1.029347,-7.514481,-1.512042,-7.857569,0.00
2,19960726,000010,0.993737,1.012498,0.975004,1.000000,20795,726116200,0.00,1.014740,...,7.065275,40.627023,22.222222,-77.777778,-1062.272727,1.042981,-5.769801,-1.648292,-5.225172,0.50
3,19960727,000010,1.012498,1.012498,0.993737,1.005005,3297,115966800,0.50,1.009495,...,4.719059,36.853552,28.236878,-71.763122,-1291.173913,1.042789,-3.941722,-1.698733,-11.641229,-0.25
4,19960729,000010,0.995020,1.013659,0.995020,0.997496,8525,300070000,-0.25,0.999493,...,2.573873,31.399853,31.415495,-68.584505,-1364.829167,1.035937,-2.787176,-1.739375,-14.331133,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807913,20220324,950210,0.992908,1.297872,0.985816,1.297872,1158787,20226315150,29.79,1.070922,...,-4.749647,67.838304,100.000000,-0.000000,-234.117647,1.093772,30.714286,-0.916953,31.861630,-3.01
6807914,20220325,950210,1.060109,1.150273,0.942623,0.969945,2884592,55832885600,-3.01,0.859563,...,2.571420,54.711042,59.756098,-40.243902,659.264706,0.858157,31.481481,0.730444,66.393691,1.69
6807915,20220328,950210,0.994366,1.022535,0.983099,1.016901,432272,7718272800,1.69,0.930141,...,8.403671,55.985908,63.414634,-36.585366,1297.205882,0.912594,33.210332,2.130543,56.425429,9.70
6807916,20220329,950210,0.991690,1.185596,0.969529,1.096953,5156123,103299163150,9.70,0.975069,...,15.800461,55.988631,81.286550,-18.713450,2238.676471,0.946046,40.425532,4.034409,75.501358,0.00
6807917,20220330,950210,1.022727,1.136364,0.982323,1.000000,2072532,43571439650,0.00,0.946465,...,21.143478,50.227010,72.020725,-27.979275,3473.676471,0.895817,48.872180,5.409680,68.857624,2.53

In [30]:
# f = open('nc추가.csv', 'r', encoding = 'cp949')
# l = f.readlines()


# encoding = 'utf-8'시 에러
# 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte
# 다음으로 인코딩 방식 수정 ==> 'utf-16', 'euc-kr', 'cp949' # cp949가 euc-kr의 확장된 버전
# 대체로 utf-16이 검색 결과 가장 많이 해결됐다던 해결책이었음.
# (https://d-p-p.tistory.com/3)


# 나의 경우 utf-16시에도 에러남
# UTF-16 stream does not start with BOM
# (https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=manhwamani&logNo=220577025526)


# readlines 부분이 문제라 feather 파일 readlines라고 검색함.
# [결과1 캐글](https://www.kaggle.com/code/kmader/convert-to-feather-for-use-in-other-kernels/notebook)
# '''
# We can save this as a feather file, which is much faster to load. But we might have to define the data types again after loading.
# '''

# [결과2 dacon tip](https://dacon.io/competitions/official/235583/codeshare/695)
# [결과3 각종 확장자 관련 공식문서](https://pandas.pydata.org/docs/user_guide/io.html)

# readlines 가능한 파일 형식 검색 결과
# [Python| 기초| (IV) 파일 처리, 내장함수 및 외장함수의 활용](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=bkyang2011&logNo=221557446577)
# [readlines 응용](https://data-make.tistory.com/109)

## 파일 입출력...
# feather 파일 입출력으로 검색한 결과
# [parquet](https://uiandwe.tistory.com/1322)
# [파일 저장형식](https://compmath.korea.ac.kr/appmath/DataLoadStorageFileFormat.html)
# [wikidocs 결과](https://wikidocs.net/75104)

In [39]:
# nc_df.info()

In [48]:
nc_df

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO,next_change
0,19960724,000010,1.000000,1.010967,0.987836,0.987836,11330,405933000,-1.22,1.004871,...,14.833178,38.017009,12.620424,-87.379576,-744.175000,1.019623,-6.344012,-1.318437,-6.161058,-1.48
1,19960725,000010,1.000000,1.000000,0.985235,0.985235,12568,442868900,-1.48,1.009856,...,10.492089,32.752921,0.000000,-100.000000,-785.980952,1.029347,-7.514481,-1.512042,-7.857569,0.00
2,19960726,000010,0.993737,1.012498,0.975004,1.000000,20795,726116200,0.00,1.014740,...,7.065275,40.627023,22.222222,-77.777778,-1062.272727,1.042981,-5.769801,-1.648292,-5.225172,0.50
3,19960727,000010,1.012498,1.012498,0.993737,1.005005,3297,115966800,0.50,1.009495,...,4.719059,36.853552,28.236878,-71.763122,-1291.173913,1.042789,-3.941722,-1.698733,-11.641229,-0.25
4,19960729,000010,0.995020,1.013659,0.995020,0.997496,8525,300070000,-0.25,0.999493,...,2.573873,31.399853,31.415495,-68.584505,-1364.829167,1.035937,-2.787176,-1.739375,-14.331133,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807913,20220324,950210,0.992908,1.297872,0.985816,1.297872,1158787,20226315150,29.79,1.070922,...,-4.749647,67.838304,100.000000,-0.000000,-234.117647,1.093772,30.714286,-0.916953,31.861630,-3.01
6807914,20220325,950210,1.060109,1.150273,0.942623,0.969945,2884592,55832885600,-3.01,0.859563,...,2.571420,54.711042,59.756098,-40.243902,659.264706,0.858157,31.481481,0.730444,66.393691,1.69
6807915,20220328,950210,0.994366,1.022535,0.983099,1.016901,432272,7718272800,1.69,0.930141,...,8.403671,55.985908,63.414634,-36.585366,1297.205882,0.912594,33.210332,2.130543,56.425429,9.70
6807916,20220329,950210,0.991690,1.185596,0.969529,1.096953,5156123,103299163150,9.70,0.975069,...,15.800461,55.988631,81.286550,-18.713450,2238.676471,0.946046,40.425532,4.034409,75.501358,0.00
6807917,20220330,950210,1.022727,1.136364,0.982323,1.000000,2072532,43571439650,0.00,0.946465,...,21.143478,50.227010,72.020725,-27.979275,3473.676471,0.895817,48.872180,5.409680,68.857624,2.53

In [9]:
nc_df['code'].nunique()

2348

## nc_df에 mk_cd 함수 적용

In [10]:
nc_df['code'] = pd.DataFrame(map(mk_cd,nc_df['code']))

In [11]:
nc_df['code'].nunique()

2348

# 조건만족 cddt에 해당하는 cd dt와 일치하는 data에 대해 그거 포함 앞 10개 날짜의 data 뽑기
* 10날짜씩 옆으로 잇기 전 test 단계

In [59]:
for iter, i in tqdm(enumerate(l)):
    i = i.strip()
    i = i.split('\t') # 리스트에 문자열로 들어감
    
    cd = i[0]
    dt = i[1]
    if iter == 0:
        pass
    else:
        dt = int(dt)
        # cd, dt
        # 각 조건 괄호로 묶어줘야 결과 출력됨.
        조건idx = nc_df.iloc[np.where((nc_df['code'] == cd) & (nc_df['date'] == dt))].index.values[0]
        nc_df.iloc[조건idx-9:조건idx+1]
# #         조건idx
#         if len(nc_df.iloc[조건idx-9:조건idx+1])!=0:
#             nc_df.iloc[조건idx-9:조건idx+1]
        break # 하나만 봐보기
f.close()

0it [00:00, ?it/s]

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO,next_change
40,19960910,000010,1.003477,1.011599,1.000000,1.004618,17585,666446300,0.46,0.998593,...,11.301074,58.207669,90.906389,-9.093611,973.867647,0.971728,8.248012,0.825861,17.541632,0.00
41,19960911,000010,1.000000,1.004624,0.989617,1.000000,19569,738559900,0.00,0.997004,...,13.150384,61.194620,90.906389,-9.093611,1016.435294,0.969712,7.979346,0.962022,12.667179,-0.12
42,19960912,000010,0.993078,1.000000,0.983857,0.998864,18725,704567800,-0.12,0.997469,...,14.540704,57.077550,89.059561,-10.940439,1048.376471,0.972185,5.617946,1.047693,8.338236,-1.39
43,19960913,000010,0.998836,0.998836,0.983813,0.986114,23287,870083500,-1.39,0.996985,...,14.031414,56.837611,71.833709,-28.166291,962.402941,0.975365,2.400571,0.989763,6.016700,-0.35
44,19960914,000010,0.996486,0.998847,0.987098,0.996486,16167,599686900,-0.35,1.008208,...,13.195258,51.944891,66.184388,-33.815612,814.035294,0.990230,2.409240,0.904950,1.995936,0.47
45,19960916,000010,0.997658,1.015289,0.997658,1.004711,22166,830147600,0.47,1.008942,...,12.940648,53.541998,72.072678,-27.927322,701.861765,0.993792,5.823316,0.865741,0.530428,1.05
46,19960917,000010,0.996490,1.010529,0.996490,1.010529,16636,622768400,1.05,1.003510,...,13.729078,58.179802,85.296097,-14.703903,639.914706,0.989905,7.204980,0.909286,-2.422356,0.00
47,19960918,000010,0.996527,1.002333,0.996527,1.000000,22616,853064600,0.00,0.992587,...,14.380319,61.261600,85.296097,-14.703903,670.514706,0.979676,1.172147,0.932735,-2.831470,-1.16
48,19960919,000010,1.002333,1.002333,0.984941,0.988414,27309,1020187000,-1.16,0.992587,...,13.395265,56.271576,39.389736,-60.610264,672.441176,0.979895,0.000000,0.846921,-1.586533,-2.70
49,19960920,000010,0.996486,1.002360,0.949600,0.973043,42732,1548596200,-2.70,0.999533,...,9.148998,48.350147,31.747185,-68.252815,570.800000,0.989047,-3.823007,0.554780,4.094900,3.13

1it [00:00,  3.51it/s]

# 10개 날짜씩 옆으로 잇기
* ten_rows 만들 때 앞 날짜(d-9)의 code가 d-0의 code와 같을 때라는 조건
* 원래 조건만족cd_dt.txt에 있던 row들 NaN값 있는 row 제거하면서 많이 사라짐...

In [64]:
all_df = pd.DataFrame()

for iter, i in tqdm(enumerate(l)):
    i = i.strip()
    i = i.split('\t') # 리스트에 문자열로 들어감

    
    cd = i[0]
    dt = i[1]
    if iter == 0:
        pass
    else:
        dt = int(dt)
#         cd, dt
#         (nc_df['code'] == cd).sum()
#         (nc_df['date'] == dt).sum()

        # code일 때 date인게 존재하면 조건idx 뽑는 코드 실행
        if (nc_df[nc_df['code'] == cd]['date']==dt).sum() == 1: # np.where를 안써도 충분히 조건에 맞는 행 찾는 거 가능했음...
            # 각 조건 괄호로 묶어줘야 결과 출력됨.
            조건idx = nc_df.iloc[np.where((nc_df['code'] == cd) & (nc_df['date'] == dt))].index.values[0]
        
        # d-9 code == d-0 code일 때
        if nc_df.iloc[조건idx-9]['code'] == nc_df.iloc[조건idx]['code']:
            ten_rows = nc_df.iloc[조건idx-9:조건idx+1]
            
        tmp = pd.DataFrame()
        for j in range(len(ten_rows)):
            t = ten_rows.iloc[[j]]
            
            # cols 바꾸기
            cols = [f'D-{9-j}_{col}' for col in t.columns]
#             cols
            t.columns = cols
#             t

            # index reset
            t = t.reset_index(drop = True)
            tmp = pd.concat([tmp, t], axis = 1)
#         tmp
        all_df = pd.concat([all_df, tmp], ignore_index = True)
#         all_df
            

f.close()

23088it [4:08:58,  1.55it/s]

KeyboardInterrupt:

In [47]:
# test cell
cnt
# 조건idx
# nc_df.iloc[조건idx-9:조건idx+1]
# nc_df

956

In [51]:
nc_df[nc_df['code']=='000020']

,date,code,open,high,low,close,volume,tradingvalue,change,ma_5,...,TSI,UO,SR,WR,AO,KAMA,ROC,PPO,PVO,next_change
2060,19960724,000020,0.997128,1.016873,0.957817,0.960689,215222,1175517000,-3.93,0.968551,...,57.463208,35.850604,28.600406,-71.399594,-48.575000,1.003140,-1.726037,2.180461,-14.549024,5.85
2061,19960725,000020,1.000000,1.058483,1.000000,1.058483,729185,4081776000,5.85,1.022795,...,55.149544,45.494762,60.344828,-39.655172,7.938095,1.044348,2.256318,2.377110,-4.108084,5.80
2062,19960726,000020,1.049779,1.058076,1.022065,1.058076,373251,2227493000,5.80,0.990044,...,54.056635,56.893374,93.711968,-6.288032,102.090909,0.987071,6.389776,2.977600,-3.895731,5.74
2063,19960727,000020,1.057391,1.057391,1.000000,1.057391,1761713,11051400000,5.74,0.964965,...,53.995760,60.626415,100.000000,-0.000000,225.282609,0.939199,9.162935,3.889945,19.539678,-0.25
2064,19960729,000020,1.000000,1.032029,0.977753,0.997476,787464,5017292000,-0.25,0.936289,...,53.822672,59.349694,85.112169,-14.887831,351.741667,0.901029,6.305700,4.513917,20.391563,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8506,20220324,000020,0.996337,1.003663,0.989011,0.996337,164839,2237216550,-0.37,1.012454,...,13.171974,35.760528,41.666667,-58.333333,1120.735294,0.714407,5.426357,1.882178,17.800975,2.21
8507,20220325,000020,1.007353,1.025735,0.992647,1.022059,248995,3420874550,2.21,1.009559,...,14.405737,37.528278,51.666667,-48.333333,926.617647,0.717033,8.171206,2.036375,11.775268,-1.08
8508,20220328,000020,1.000000,1.000000,0.978417,0.989209,160036,2199989250,-1.08,0.986331,...,14.679373,38.444619,46.666667,-53.333333,797.500000,0.701558,6.589147,2.043365,5.081122,0.00
8509,20220329,000020,1.007273,1.018182,0.992727,1.000000,160334,2217001550,0.00,0.998545,...,14.901820,34.770059,46.666667,-53.333333,746.323529,0.709211,7.003891,2.024711,-0.709612,1.09
8510,20220330,000020,1.003636,1.032727,1.000000,1.010909,365447,5121033250,1.09,1.002182,...,15.637726,38.244670,51.666667,-48.333333,727.941176,0.709211,10.756972,2.074455,-1.416792,-1.80